package net.hedtech.general.common.libraries.Goqorep;

import java.util.*;
import org.jdesktop.databuffer.DataRow.DataRowStatus;

import morphis.foundations.core.appdatalayer.*;
import morphis.foundations.core.appdatalayer.data.*;
import morphis.foundations.core.types.*;
import morphis.foundations.core.appsupportlib.*;
import morphis.foundations.core.appsupportlib.exceptions.*;
import morphis.foundations.core.appsupportlib.model.*;
import morphis.foundations.core.appsupportlib.util.*;
import morphis.foundations.core.appsupportlib.runtime.*;
import morphis.foundations.core.appsupportlib.runtime.controlsModel.items.*;
import morphis.foundations.core.appsupportlib.runtime.controlsModel.lovs.*;
import morphis.foundations.core.appsupportlib.runtime.controlsModel.containers.*;
import morphis.foundations.core.appsupportlib.runtime.controlsModel.alerts.*;
import static morphis.foundations.core.appsupportlib.runtime.TaskServices.*;
import static morphis.foundations.core.appsupportlib.runtime.ItemServices.*;
import static morphis.foundations.core.appsupportlib.runtime.BlockServices.*;
import static morphis.foundations.core.appsupportlib.runtime.ViewServices.*;
import static morphis.foundations.core.appsupportlib.runtime.MessageServices.*;
import static morphis.foundations.core.appsupportlib.runtime.ValueSetServices.*;
import static morphis.foundations.core.appsupportlib.runtime.LovServices.*;
import static morphis.foundations.core.appsupportlib.Math.*;
import static morphis.foundations.core.appsupportlib.Lib.*;
import static morphis.foundations.core.appsupportlib.Globals.*;
import static morphis.foundations.core.types.Types.*;
import morphis.foundations.core.util.*;

import net.hedtech.general.common.dbservices.*;
import net.hedtech.general.common.dbservices.dbtypes.*;


public class Exception_ extends AbstractSupportCodeObject {
	

	public Exception_(ISupportCodeContainer container) {
		super(container);
	}
	
	@Override
	public GoqorepServices getContainer() {
		return (GoqorepServices)super.getContainer();
	}
	//Original PL/SQL code for Package Prog Unit (SPEC) EXCEPTION_
	/*
	PACKAGE Exception_ <multilinecomment> java.lang.Exception </multilinecomment> IS

  -- 
  -- DO NOT EDIT THIS FILE - it is machine generated!
  -- 


  -- Constructor for signature (Ljava/lang/String;)V
  FUNCTION new(
    a0    VARCHAR2) RETURN ORA_JAVA.JOBJECT;

  -- Constructor for signature (Ljava/lang/Exception;)V
  FUNCTION new(
    a0    ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JOBJECT;

  -- Constructor for signature (Ljava/lang/String;Ljava/lang/Exception;)V
  FUNCTION new(
    a0    VARCHAR2,
    a1    ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JOBJECT;

  -- Constructor for signature ()V
  FUNCTION new RETURN ORA_JAVA.JOBJECT;

  -- Method: printStackTrace (Ljava/io/PrintStream;)V
  PROCEDURE printStackTrace_0(
    obj   ORA_JAVA.JOBJECT,
    a0    ORA_JAVA.JOBJECT);

  -- Method: printStackTrace ()V
  PROCEDURE printStackTrace(
    obj   ORA_JAVA.JOBJECT);

  -- Method: printStackTrace (Ljava/io/PrintWriter;)V
  PROCEDURE printStackTrace_1(
    obj   ORA_JAVA.JOBJECT,
    a0    ORA_JAVA.JOBJECT);

  -- Method: fillInStackTrace ()Ljava/lang/Exception;
  FUNCTION fillInStackTrace(
    obj   ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JOBJECT;

  -- Method: toString ()Ljava/lang/String;
  FUNCTION toString(
    obj   ORA_JAVA.JOBJECT) RETURN VARCHAR2;

  -- Method: initCause (Ljava/lang/Exception;)Ljava/lang/Exception;
  FUNCTION initCause(
    obj   ORA_JAVA.JOBJECT,
    a0    ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JOBJECT;

  -- Method: getCause ()Ljava/lang/Exception;
  FUNCTION getCause(
    obj   ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JOBJECT;

  -- Method: getLocalizedMessage ()Ljava/lang/String;
  FUNCTION getLocalizedMessage(
    obj   ORA_JAVA.JOBJECT) RETURN VARCHAR2;

  -- Method: getMessage ()Ljava/lang/String;
  FUNCTION getMessage(
    obj   ORA_JAVA.JOBJECT) RETURN VARCHAR2;

  -- Method: getStackTrace ()[Ljava/lang/StackTraceElement;
  FUNCTION getStackTrace(
    obj   ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JARRAY;

  -- Method: setStackTrace ([Ljava/lang/StackTraceElement;)V
  PROCEDURE setStackTrace(
    obj   ORA_JAVA.JOBJECT,
    a0    ORA_JAVA.JARRAY);

  -- Method: hashCode ()I
  FUNCTION hashCode(
    obj   ORA_JAVA.JOBJECT) RETURN NUMBER;

  -- Method: getClass ()Ljava/lang/Class;
  FUNCTION getClass(
    obj   ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JOBJECT;

  -- Method: wait ()V
  PROCEDURE wait(
    obj   ORA_JAVA.JOBJECT);

  -- Method: wait (J)V
  PROCEDURE wait(
    obj   ORA_JAVA.JOBJECT,
    a0    NUMBER);

  -- Method: wait (JI)V
  PROCEDURE wait(
    obj   ORA_JAVA.JOBJECT,
    a0    NUMBER,
    a1    NUMBER);

  -- Method: equals (Ljava/lang/Object;)Z
  FUNCTION equals(
    obj   ORA_JAVA.JOBJECT,
    a0    ORA_JAVA.JOBJECT) RETURN BOOLEAN;

  -- Method: notify ()V
  PROCEDURE notify(
    obj   ORA_JAVA.JOBJECT);

  -- Method: notifyAll ()V
  PROCEDURE notifyAll(
    obj   ORA_JAVA.JOBJECT);

END;
	*/
	
	
			
		//Original PL/SQL code for Package Prog Unit (BODY) EXCEPTION_
		/*
		PACKAGE BODY Exception_ IS

  -- 
  -- DO NOT EDIT THIS FILE - it is machine generated!
  -- 

  args   JNI.ARGLIST;

  -- Constructor for signature (Ljava/lang/String;)V
  FUNCTION new(
    a0    VARCHAR2) RETURN ORA_JAVA.JOBJECT IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_STRING_ARG(args, a0);
    RETURN (JNI.NEW_OBJECT('java/lang/Exception', '(Ljava/lang/String;)V', args));
  END;

  -- Constructor for signature (Ljava/lang/Exception;)V
  FUNCTION new(
    a0    ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JOBJECT IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_OBJECT_ARG(args, a0, 'java/lang/Exception');
    RETURN (JNI.NEW_OBJECT('java/lang/Exception', '(Ljava/lang/Exception;)V', args));
  END;

  -- Constructor for signature (Ljava/lang/String;Ljava/lang/Exception;)V
  FUNCTION new(
    a0    VARCHAR2,
    a1    ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JOBJECT IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(2);
    JNI.ADD_STRING_ARG(args, a0);
    JNI.ADD_OBJECT_ARG(args, a1, 'java/lang/Exception');
    RETURN (JNI.NEW_OBJECT('java/lang/Exception', '(Ljava/lang/String;Ljava/lang/Exception;)V', args));
  END;

  -- Constructor for signature ()V
  FUNCTION new RETURN ORA_JAVA.JOBJECT IS
  BEGIN
    args := NULL;
    RETURN (JNI.NEW_OBJECT('java/lang/Exception', '()V', args));
  END;

  -- Method: printStackTrace (Ljava/io/PrintStream;)V
  PROCEDURE printStackTrace_0(
    obj   ORA_JAVA.JOBJECT,
    a0    ORA_JAVA.JOBJECT) IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_OBJECT_ARG(args, a0, 'java/io/PrintStream');
    JNI.CALL_VOID_METHOD(FALSE, obj, 'java/lang/Exception', 'printStackTrace', '(Ljava/io/PrintStream;)V', args); 
  END;

  -- Method: printStackTrace ()V
  PROCEDURE printStackTrace(
    obj   ORA_JAVA.JOBJECT) IS
  BEGIN
    args := NULL;
    JNI.CALL_VOID_METHOD(FALSE, obj, 'java/lang/Exception', 'printStackTrace', '()V', args); 
  END;

  -- Method: printStackTrace (Ljava/io/PrintWriter;)V
  PROCEDURE printStackTrace_1(
    obj   ORA_JAVA.JOBJECT,
    a0    ORA_JAVA.JOBJECT) IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_OBJECT_ARG(args, a0, 'java/io/PrintWriter');
    JNI.CALL_VOID_METHOD(FALSE, obj, 'java/lang/Exception', 'printStackTrace', '(Ljava/io/PrintWriter;)V', args); 
  END;

  -- Method: fillInStackTrace ()Ljava/lang/Exception;
  FUNCTION fillInStackTrace(
    obj   ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JOBJECT IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_OBJECT_METHOD(FALSE, obj, 'java/lang/Exception', 'fillInStackTrace', '()Ljava/lang/Exception;', args); 
  END;

  -- Method: toString ()Ljava/lang/String;
  FUNCTION toString(
    obj   ORA_JAVA.JOBJECT) RETURN VARCHAR2 IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_STRING_METHOD(FALSE, obj, 'java/lang/Exception', 'toString', '()Ljava/lang/String;', args); 
  END;

  -- Method: initCause (Ljava/lang/Exception;)Ljava/lang/Exception;
  FUNCTION initCause(
    obj   ORA_JAVA.JOBJECT,
    a0    ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JOBJECT IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_OBJECT_ARG(args, a0, 'java/lang/Exception');
    RETURN JNI.CALL_OBJECT_METHOD(FALSE, obj, 'java/lang/Exception', 'initCause', '(Ljava/lang/Exception;)Ljava/lang/Exception;', args); 
  END;

  -- Method: getCause ()Ljava/lang/Exception;
  FUNCTION getCause(
    obj   ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JOBJECT IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_OBJECT_METHOD(FALSE, obj, 'java/lang/Exception', 'getCause', '()Ljava/lang/Exception;', args); 
  END;

  -- Method: getLocalizedMessage ()Ljava/lang/String;
  FUNCTION getLocalizedMessage(
    obj   ORA_JAVA.JOBJECT) RETURN VARCHAR2 IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_STRING_METHOD(FALSE, obj, 'java/lang/Exception', 'getLocalizedMessage', '()Ljava/lang/String;', args); 
  END;

  -- Method: getMessage ()Ljava/lang/String;
  FUNCTION getMessage(
    obj   ORA_JAVA.JOBJECT) RETURN VARCHAR2 IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_STRING_METHOD(FALSE, obj, 'java/lang/Exception', 'getMessage', '()Ljava/lang/String;', args); 
  END;

  -- Method: getStackTrace ()[Ljava/lang/StackTraceElement;
  FUNCTION getStackTrace(
    obj   ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JARRAY IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_OBJECT_METHOD(FALSE, obj, 'java/lang/Exception', 'getStackTrace', '()[Ljava/lang/StackTraceElement;', args); 
  END;

  -- Method: setStackTrace ([Ljava/lang/StackTraceElement;)V
  PROCEDURE setStackTrace(
    obj   ORA_JAVA.JOBJECT,
    a0    ORA_JAVA.JARRAY) IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_OBJECT_ARG(args, a0, '[Ljava/lang/StackTraceElement;');
    JNI.CALL_VOID_METHOD(FALSE, obj, 'java/lang/Exception', 'setStackTrace', '([Ljava/lang/StackTraceElement;)V', args); 
  END;

  -- Method: hashCode ()I
  FUNCTION hashCode(
    obj   ORA_JAVA.JOBJECT) RETURN NUMBER IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_INT_METHOD(FALSE, obj, 'java/lang/Exception', 'hashCode', '()I', args); 
  END;

  -- Method: getClass ()Ljava/lang/Class;
  FUNCTION getClass(
    obj   ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JOBJECT IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_OBJECT_METHOD(FALSE, obj, 'java/lang/Exception', 'getClass', '()Ljava/lang/Class;', args); 
  END;

  -- Method: wait ()V
  PROCEDURE wait(
    obj   ORA_JAVA.JOBJECT) IS
  BEGIN
    args := NULL;
    JNI.CALL_VOID_METHOD(FALSE, obj, 'java/lang/Exception', 'wait', '()V', args); 
  END;

  -- Method: wait (J)V
  PROCEDURE wait(
    obj   ORA_JAVA.JOBJECT,
    a0    NUMBER) IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_LONG_ARG(args, a0);
    JNI.CALL_VOID_METHOD(FALSE, obj, 'java/lang/Exception', 'wait', '(J)V', args); 
  END;

  -- Method: wait (JI)V
  PROCEDURE wait(
    obj   ORA_JAVA.JOBJECT,
    a0    NUMBER,
    a1    NUMBER) IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(2);
    JNI.ADD_LONG_ARG(args, a0);
    JNI.ADD_INT_ARG(args, a1);
    JNI.CALL_VOID_METHOD(FALSE, obj, 'java/lang/Exception', 'wait', '(JI)V', args); 
  END;

  -- Method: equals (Ljava/lang/Object;)Z
  FUNCTION equals(
    obj   ORA_JAVA.JOBJECT,
    a0    ORA_JAVA.JOBJECT) RETURN BOOLEAN IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_OBJECT_ARG(args, a0, 'java/lang/Object');
    RETURN JNI.CALL_BOOLEAN_METHOD(FALSE, obj, 'java/lang/Exception', 'equals', '(Ljava/lang/Object;)Z', args); 
  END;

  -- Method: notify ()V
  PROCEDURE notify(
    obj   ORA_JAVA.JOBJECT) IS
  BEGIN
    args := NULL;
    JNI.CALL_VOID_METHOD(FALSE, obj, 'java/lang/Exception', 'notify', '()V', args); 
  END;

  -- Method: notifyAll ()V
  PROCEDURE notifyAll(
    obj   ORA_JAVA.JOBJECT) IS
  BEGIN
    args := NULL;
    JNI.CALL_VOID_METHOD(FALSE, obj, 'java/lang/Exception', 'notifyAll', '()V', args); 
  END;


BEGIN
  NULL;
END;
		*/
				//  
		//  DO NOT EDIT THIS FILE - it is machine generated!
		//  
		private UnknownTypes.JniArglist args= null;
/* <p>
		*  Constructor for signature (Ljava/lang/String;)V
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param a0
		*/
		public UnknownTypes.OraJavaJobject _new(NString a0)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin10".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin10'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_STRING_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin11".
//			//			SupportClasses.JNI.AddStringArg(args, a0);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_STRING_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin11'.");
//			
//			return ((SupportClasses.JNI.NewObject("java/lang/Exception", "(Ljava/lang/String;)V", args)));
//
			this.getLogger().trace(this, "F2J : _new function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return null;
		}
/* <p>
		*  Constructor for signature (Ljava/lang/Exception;)V
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param a0
		*/
		public UnknownTypes.OraJavaJobject _new(UnknownTypes.OraJavaJobject a0)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin10".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin10'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_OBJECT_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin12".
//			//			SupportClasses.JNI.AddObjectArg(args, a0, "java/lang/Exception");
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_OBJECT_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin12'.");
//			
//			return ((SupportClasses.JNI.NewObject("java/lang/Exception", "(Ljava/lang/Exception;)V", args)));
//
			this.getLogger().trace(this, "F2J : _new function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return null;
		}
/* <p>
		*  Constructor for signature (Ljava/lang/String;Ljava/lang/Exception;)V
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param a0
		* @param a1
		*/
		public UnknownTypes.OraJavaJobject _new(NString a0, UnknownTypes.OraJavaJobject a1)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin10".
//			//			args = SupportClasses.JNI.CreateArgList(2);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin10'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_STRING_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin11".
//			//			SupportClasses.JNI.AddStringArg(args, a0);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_STRING_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin11'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_OBJECT_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin12".
//			//			SupportClasses.JNI.AddObjectArg(args, a1, "java/lang/Exception");
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_OBJECT_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin12'.");
//			
//			return ((SupportClasses.JNI.NewObject("java/lang/Exception", "(Ljava/lang/String;Ljava/lang/Exception;)V", args)));
//
			this.getLogger().trace(this, "F2J : _new function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return null;
		}
/* <p>
		*  Constructor for signature ()V
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		*/
		public UnknownTypes.OraJavaJobject _new()
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return ((SupportClasses.JNI.NewObject("java/lang/Exception", "()V", args)));
//
			this.getLogger().trace(this, "F2J : _new function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return null;
		}
/* <p>
		*  Method: printStackTrace (Ljava/io/PrintStream;)V
		* F2J_PURE_BUSINESS_LOGIC : The code of this procedure was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		* @param a0
		*/
		public void printstacktrace0(UnknownTypes.OraJavaJobject obj, UnknownTypes.OraJavaJobject a0)
		{
			//F2J_WRAPPED_CODE : The code of this Procedure was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin10".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin10'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_OBJECT_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin12".
//			//			SupportClasses.JNI.AddObjectArg(args, a0, "java/io/PrintStream");
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_OBJECT_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin12'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "CALL_VOID_METHOD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin13".
//			//			SupportClasses.JNI.CallVoidMethod(NBool.False, obj, "java/lang/Exception", "printStackTrace", "(Ljava/io/PrintStream;)V", args);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CALL_VOID_METHOD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin13'.");
//			
//
			this.getLogger().trace(this, "F2J : printstacktrace0 procedure is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
/* <p>
		*  Method: printStackTrace ()V
		* F2J_PURE_BUSINESS_LOGIC : The code of this procedure was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public void printstacktrace(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Procedure was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			// F2J_NOT_SUPPORTED : Call to built-in "CALL_VOID_METHOD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin13".
//			//			SupportClasses.JNI.CallVoidMethod(NBool.False, obj, "java/lang/Exception", "printStackTrace", "()V", args);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CALL_VOID_METHOD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin13'.");
//			
//
			this.getLogger().trace(this, "F2J : printstacktrace procedure is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
/* <p>
		*  Method: printStackTrace (Ljava/io/PrintWriter;)V
		* F2J_PURE_BUSINESS_LOGIC : The code of this procedure was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		* @param a0
		*/
		public void printstacktrace1(UnknownTypes.OraJavaJobject obj, UnknownTypes.OraJavaJobject a0)
		{
			//F2J_WRAPPED_CODE : The code of this Procedure was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin10".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin10'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_OBJECT_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin12".
//			//			SupportClasses.JNI.AddObjectArg(args, a0, "java/io/PrintWriter");
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_OBJECT_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin12'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "CALL_VOID_METHOD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin13".
//			//			SupportClasses.JNI.CallVoidMethod(NBool.False, obj, "java/lang/Exception", "printStackTrace", "(Ljava/io/PrintWriter;)V", args);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CALL_VOID_METHOD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin13'.");
//			
//
			this.getLogger().trace(this, "F2J : printstacktrace1 procedure is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
/* <p>
		*  Method: fillInStackTrace ()Ljava/lang/Exception;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public UnknownTypes.OraJavaJobject fillinstacktrace(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallObjectMethod(NBool.False, obj, "java/lang/Exception", "fillInStackTrace", "()Ljava/lang/Exception;", args);
//
			this.getLogger().trace(this, "F2J : fillinstacktrace function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return null;
		}
/* <p>
		*  Method: toString ()Ljava/lang/String;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public NString tostring(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallStringMethod(NBool.False, obj, "java/lang/Exception", "toString", "()Ljava/lang/String;", args);
//
			this.getLogger().trace(this, "F2J : tostring function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NString.getNull();
		}
/* <p>
		*  Method: initCause (Ljava/lang/Exception;)Ljava/lang/Exception;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		* @param a0
		*/
		public UnknownTypes.OraJavaJobject initcause(UnknownTypes.OraJavaJobject obj, UnknownTypes.OraJavaJobject a0)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin10".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin10'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_OBJECT_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin12".
//			//			SupportClasses.JNI.AddObjectArg(args, a0, "java/lang/Exception");
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_OBJECT_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin12'.");
//			
//			return SupportClasses.JNI.CallObjectMethod(NBool.False, obj, "java/lang/Exception", "initCause", "(Ljava/lang/Exception;)Ljava/lang/Exception;", args);
//
			this.getLogger().trace(this, "F2J : initcause function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return null;
		}
/* <p>
		*  Method: getCause ()Ljava/lang/Exception;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public UnknownTypes.OraJavaJobject getcause(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallObjectMethod(NBool.False, obj, "java/lang/Exception", "getCause", "()Ljava/lang/Exception;", args);
//
			this.getLogger().trace(this, "F2J : getcause function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return null;
		}
/* <p>
		*  Method: getLocalizedMessage ()Ljava/lang/String;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public NString getlocalizedmessage(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallStringMethod(NBool.False, obj, "java/lang/Exception", "getLocalizedMessage", "()Ljava/lang/String;", args);
//
			this.getLogger().trace(this, "F2J : getlocalizedmessage function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NString.getNull();
		}
/* <p>
		*  Method: getMessage ()Ljava/lang/String;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public NString getmessage(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallStringMethod(NBool.False, obj, "java/lang/Exception", "getMessage", "()Ljava/lang/String;", args);
//
			this.getLogger().trace(this, "F2J : getmessage function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NString.getNull();
		}
/* <p>
		*  Method: getStackTrace ()[Ljava/lang/StackTraceElement;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public UnknownTypes.OraJavaJarray getstacktrace(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallObjectMethod(NBool.False, obj, "java/lang/Exception", "getStackTrace", "()[Ljava/lang/StackTraceElement;", args);
//
			this.getLogger().trace(this, "F2J : getstacktrace function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return null;
		}
/* <p>
		*  Method: setStackTrace ([Ljava/lang/StackTraceElement;)V
		* F2J_PURE_BUSINESS_LOGIC : The code of this procedure was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		* @param a0
		*/
		public void setstacktrace(UnknownTypes.OraJavaJobject obj, UnknownTypes.OraJavaJarray a0)
		{
			//F2J_WRAPPED_CODE : The code of this Procedure was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin10".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin10'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_OBJECT_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin12".
//			//			SupportClasses.JNI.AddObjectArg(args, a0, "[Ljava/lang/StackTraceElement;");
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_OBJECT_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin12'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "CALL_VOID_METHOD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin13".
//			//			SupportClasses.JNI.CallVoidMethod(NBool.False, obj, "java/lang/Exception", "setStackTrace", "([Ljava/lang/StackTraceElement;)V", args);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CALL_VOID_METHOD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin13'.");
//			
//
			this.getLogger().trace(this, "F2J : setstacktrace procedure is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
/* <p>
		*  Method: hashCode ()I
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public NNumber hashcode(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallIntMethod(NBool.False, obj, "java/lang/Exception", "hashCode", "()I", args);
//
			this.getLogger().trace(this, "F2J : hashcode function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NNumber.getNull();
		}
/* <p>
		*  Method: getClass ()Ljava/lang/Class;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public UnknownTypes.OraJavaJobject getclass(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallObjectMethod(NBool.False, obj, "java/lang/Exception", "getClass", "()Ljava/lang/Class;", args);
//
			this.getLogger().trace(this, "F2J : getclass function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return null;
		}
/* <p>
		*  Method: wait ()V
		* F2J_PURE_BUSINESS_LOGIC : The code of this procedure was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public void wait(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Procedure was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			// F2J_NOT_SUPPORTED : Call to built-in "CALL_VOID_METHOD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin13".
//			//			SupportClasses.JNI.CallVoidMethod(NBool.False, obj, "java/lang/Exception", "wait", "()V", args);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CALL_VOID_METHOD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin13'.");
//			
//
			this.getLogger().trace(this, "F2J : wait procedure is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
/* <p>
		*  Method: wait (J)V
		* F2J_PURE_BUSINESS_LOGIC : The code of this procedure was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		* @param a0
		*/
		public void wait(UnknownTypes.OraJavaJobject obj, NNumber a0)
		{
			//F2J_WRAPPED_CODE : The code of this Procedure was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin10".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin10'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_LONG_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin14".
//			//			SupportClasses.JNI.AddLongArg(args, a0);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_LONG_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin14'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "CALL_VOID_METHOD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin13".
//			//			SupportClasses.JNI.CallVoidMethod(NBool.False, obj, "java/lang/Exception", "wait", "(J)V", args);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CALL_VOID_METHOD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin13'.");
//			
//
			this.getLogger().trace(this, "F2J : wait procedure is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
/* <p>
		*  Method: wait (JI)V
		* F2J_PURE_BUSINESS_LOGIC : The code of this procedure was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		* @param a0
		* @param a1
		*/
		public void wait(UnknownTypes.OraJavaJobject obj, NNumber a0, NNumber a1)
		{
			//F2J_WRAPPED_CODE : The code of this Procedure was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin10".
//			//			args = SupportClasses.JNI.CreateArgList(2);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin10'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_LONG_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin14".
//			//			SupportClasses.JNI.AddLongArg(args, a0);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_LONG_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin14'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_INT_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin15".
//			//			SupportClasses.JNI.AddIntArg(args, a1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_INT_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin15'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "CALL_VOID_METHOD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin13".
//			//			SupportClasses.JNI.CallVoidMethod(NBool.False, obj, "java/lang/Exception", "wait", "(JI)V", args);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CALL_VOID_METHOD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin13'.");
//			
//
			this.getLogger().trace(this, "F2J : wait procedure is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
/* <p>
		*  Method: equals (Ljava/lang/Object;)Z
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		* @param a0
		*/
		public NBool equals(UnknownTypes.OraJavaJobject obj, UnknownTypes.OraJavaJobject a0)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin10".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin10'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_OBJECT_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin12".
//			//			SupportClasses.JNI.AddObjectArg(args, a0, "java/lang/Object");
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_OBJECT_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin12'.");
//			
//			return SupportClasses.JNI.CallBooleanMethod(NBool.False, obj, "java/lang/Exception", "equals", "(Ljava/lang/Object;)Z", args);
//
			this.getLogger().trace(this, "F2J : equals function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NBool.getNull();
		}
/* <p>
		*  Method: notify ()V
		* F2J_PURE_BUSINESS_LOGIC : The code of this procedure was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public void notify(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Procedure was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			// F2J_NOT_SUPPORTED : Call to built-in "CALL_VOID_METHOD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin13".
//			//			SupportClasses.JNI.CallVoidMethod(NBool.False, obj, "java/lang/Exception", "notify", "()V", args);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CALL_VOID_METHOD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin13'.");
//			
//
			this.getLogger().trace(this, "F2J : notify procedure is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
/* <p>
		*  Method: notifyAll ()V
		* F2J_PURE_BUSINESS_LOGIC : The code of this procedure was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public void notifyall(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Procedure was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			// F2J_NOT_SUPPORTED : Call to built-in "CALL_VOID_METHOD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin13".
//			//			SupportClasses.JNI.CallVoidMethod(NBool.False, obj, "java/lang/Exception", "notifyAll", "()V", args);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CALL_VOID_METHOD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\GOQOREPF2NMigrationGuide.xml#DefaultExcludeBuiltin13'.");
//			
//
			this.getLogger().trace(this, "F2J : notifyall procedure is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
		
	
	
}
