package net.hedtech.general.common.libraries.Webutil;

import java.util.*;
import org.jdesktop.databuffer.DataRow.DataRowStatus;

import morphis.foundations.core.appdatalayer.*;
import morphis.foundations.core.appdatalayer.data.*;
import morphis.foundations.core.types.*;
import morphis.foundations.core.appsupportlib.*;
import morphis.foundations.core.appsupportlib.exceptions.*;
import morphis.foundations.core.appsupportlib.model.*;
import morphis.foundations.core.appsupportlib.util.*;
import morphis.foundations.core.appsupportlib.runtime.*;
import morphis.foundations.core.appsupportlib.runtime.controlsModel.items.*;
import morphis.foundations.core.appsupportlib.runtime.controlsModel.lovs.*;
import morphis.foundations.core.appsupportlib.runtime.controlsModel.containers.*;
import morphis.foundations.core.appsupportlib.runtime.controlsModel.alerts.*;
import static morphis.foundations.core.appsupportlib.runtime.TaskServices.*;
import static morphis.foundations.core.appsupportlib.runtime.ItemServices.*;
import static morphis.foundations.core.appsupportlib.runtime.BlockServices.*;
import static morphis.foundations.core.appsupportlib.runtime.ViewServices.*;
import static morphis.foundations.core.appsupportlib.runtime.MessageServices.*;
import static morphis.foundations.core.appsupportlib.runtime.ValueSetServices.*;
import static morphis.foundations.core.appsupportlib.runtime.LovServices.*;
import static morphis.foundations.core.appsupportlib.Math.*;
import static morphis.foundations.core.appsupportlib.Lib.*;
import static morphis.foundations.core.appsupportlib.Globals.*;
import static morphis.foundations.core.types.Types.*;
import morphis.foundations.core.util.*;

import net.hedtech.general.common.dbservices.*;
import net.hedtech.general.common.dbservices.dbtypes.*;


public class JavaFile extends AbstractSupportCodeObject {
	

	public JavaFile(ISupportCodeContainer container) {
		super(container);
	}
	
	@Override
	public WebutilServices getContainer() {
		return (WebutilServices)super.getContainer();
	}
	//Original PL/SQL code for Package Prog Unit (SPEC) JAVA_FILE
	/*
	PACKAGE JAVA_FILE <multilinecomment> java.io.File </multilinecomment> IS

  -- 
  -- DO NOT EDIT THIS FILE - it is machine generated!
  -- 
  separatorChar  PLS_INTEGER;  -- separatorChar
  separator  VARCHAR2(256);  -- separator
  pathSeparatorChar  PLS_INTEGER;  -- pathSeparatorChar
  pathSeparator  VARCHAR2(256);  -- pathSeparator


  -- Constructor for signature (Ljava/io/File;Ljava/lang/String;)V
  FUNCTION new(
    a0    ORA_JAVA.JOBJECT,
    a1    VARCHAR2) RETURN ORA_JAVA.JOBJECT;

  -- Constructor for signature (Ljava/net/URI;)V
  FUNCTION new(
    a0    ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JOBJECT;

  -- Constructor for signature (Ljava/lang/String;)V
  FUNCTION new(
    a0    VARCHAR2) RETURN ORA_JAVA.JOBJECT;

  -- Constructor for signature (Ljava/lang/String;Ljava/lang/String;)V
  FUNCTION new(
    a0    VARCHAR2,
    a1    VARCHAR2) RETURN ORA_JAVA.JOBJECT;

  -- Method: hashCode ()I
  FUNCTION hashCode(
    obj   ORA_JAVA.JOBJECT) RETURN NUMBER;

  -- Method: compareTo (Ljava/io/File;)I
  FUNCTION compareTo_0(
    obj   ORA_JAVA.JOBJECT,
    a0    ORA_JAVA.JOBJECT) RETURN NUMBER;

  -- Method: compareTo (Ljava/lang/Object;)I
  FUNCTION compareTo_1(
    obj   ORA_JAVA.JOBJECT,
    a0    ORA_JAVA.JOBJECT) RETURN NUMBER;

  -- Method: equals (Ljava/lang/Object;)Z
  FUNCTION equals(
    obj   ORA_JAVA.JOBJECT,
    a0    ORA_JAVA.JOBJECT) RETURN BOOLEAN;

  -- Method: getName ()Ljava/lang/String;
  FUNCTION getName(
    obj   ORA_JAVA.JOBJECT) RETURN VARCHAR2;

  -- Method: toString ()Ljava/lang/String;
  FUNCTION toString(
    obj   ORA_JAVA.JOBJECT) RETURN VARCHAR2;

  -- Method: length ()J
  FUNCTION length(
    obj   ORA_JAVA.JOBJECT) RETURN NUMBER;

  -- Method: getCanonicalPath ()Ljava/lang/String;
  FUNCTION getCanonicalPath(
    obj   ORA_JAVA.JOBJECT) RETURN VARCHAR2;

  -- Method: getParent ()Ljava/lang/String;
  FUNCTION getParent(
    obj   ORA_JAVA.JOBJECT) RETURN VARCHAR2;

  -- Method: isAbsolute ()Z
  FUNCTION isAbsolute(
    obj   ORA_JAVA.JOBJECT) RETURN BOOLEAN;

  -- Method: setReadOnly ()Z
  FUNCTION setReadOnly(
    obj   ORA_JAVA.JOBJECT) RETURN BOOLEAN;

  -- Method: list ()[Ljava/lang/String;
  FUNCTION list(
    obj   ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JARRAY;

  -- Method: list (Ljava/io/FilenameFilter;)[Ljava/lang/String;
  FUNCTION list(
    obj   ORA_JAVA.JOBJECT,
    a0    ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JARRAY;

  -- Method: delete ()Z
  FUNCTION delete_(
    obj   ORA_JAVA.JOBJECT) RETURN BOOLEAN;

  -- Method: getPath ()Ljava/lang/String;
  FUNCTION getPath(
    obj   ORA_JAVA.JOBJECT) RETURN VARCHAR2;

  -- Method: canRead ()Z
  FUNCTION canRead(
    obj   ORA_JAVA.JOBJECT) RETURN BOOLEAN;

  -- Method: canWrite ()Z
  FUNCTION canWrite(
    obj   ORA_JAVA.JOBJECT) RETURN BOOLEAN;

  -- Method: createNewFile ()Z
  FUNCTION createNewFile(
    obj   ORA_JAVA.JOBJECT) RETURN BOOLEAN;

  -- Method: createTempFile (Ljava/lang/String;Ljava/lang/String;)Ljava/io/File;
  FUNCTION createTempFile(
    a0    VARCHAR2,
    a1    VARCHAR2) RETURN ORA_JAVA.JOBJECT;

  -- Method: createTempFile (Ljava/lang/String;Ljava/lang/String;Ljava/io/File;)Ljava/io/File;
  FUNCTION createTempFile(
    a0    VARCHAR2,
    a1    VARCHAR2,
    a2    ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JOBJECT;

  -- Method: deleteOnExit ()V
  PROCEDURE deleteOnExit(
    obj   ORA_JAVA.JOBJECT);

  -- Method: exists ()Z
  FUNCTION exists_(
    obj   ORA_JAVA.JOBJECT) RETURN BOOLEAN;

  -- Method: getAbsoluteFile ()Ljava/io/File;
  FUNCTION getAbsoluteFile(
    obj   ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JOBJECT;

  -- Method: getAbsolutePath ()Ljava/lang/String;
  FUNCTION getAbsolutePath(
    obj   ORA_JAVA.JOBJECT) RETURN VARCHAR2;

  -- Method: getCanonicalFile ()Ljava/io/File;
  FUNCTION getCanonicalFile(
    obj   ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JOBJECT;

  -- Method: getParentFile ()Ljava/io/File;
  FUNCTION getParentFile(
    obj   ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JOBJECT;

  -- Method: isDirectory ()Z
  FUNCTION isDirectory(
    obj   ORA_JAVA.JOBJECT) RETURN BOOLEAN;

  -- Method: isFile ()Z
  FUNCTION isFile(
    obj   ORA_JAVA.JOBJECT) RETURN BOOLEAN;

  -- Method: isHidden ()Z
  FUNCTION isHidden(
    obj   ORA_JAVA.JOBJECT) RETURN BOOLEAN;

  -- Method: lastModified ()J
  FUNCTION lastModified(
    obj   ORA_JAVA.JOBJECT) RETURN NUMBER;

  -- Method: listFiles (Ljava/io/FileFilter;)[Ljava/io/File;
  FUNCTION listFiles_0(
    obj   ORA_JAVA.JOBJECT,
    a0    ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JARRAY;

  -- Method: listFiles (Ljava/io/FilenameFilter;)[Ljava/io/File;
  FUNCTION listFiles_1(
    obj   ORA_JAVA.JOBJECT,
    a0    ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JARRAY;

  -- Method: listFiles ()[Ljava/io/File;
  FUNCTION listFiles(
    obj   ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JARRAY;

  -- Method: listRoots ()[Ljava/io/File;
  FUNCTION listRoots RETURN ORA_JAVA.JARRAY;

  -- Method: mkdir ()Z
  FUNCTION mkdir(
    obj   ORA_JAVA.JOBJECT) RETURN BOOLEAN;

  -- Method: mkdirs ()Z
  FUNCTION mkdirs(
    obj   ORA_JAVA.JOBJECT) RETURN BOOLEAN;

  -- Method: renameTo (Ljava/io/File;)Z
  FUNCTION renameTo(
    obj   ORA_JAVA.JOBJECT,
    a0    ORA_JAVA.JOBJECT) RETURN BOOLEAN;

  -- Method: setLastModified (J)Z
  FUNCTION setLastModified(
    obj   ORA_JAVA.JOBJECT,
    a0    NUMBER) RETURN BOOLEAN;

  -- Method: toURI ()Ljava/net/URI;
  FUNCTION toURI(
    obj   ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JOBJECT;

  -- Method: toURL ()Ljava/net/URL;
  FUNCTION toURL(
    obj   ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JOBJECT;

  -- Method: getClass ()Ljava/lang/Class;
  FUNCTION getClass(
    obj   ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JOBJECT;

  -- Method: wait (JI)V
  PROCEDURE wait(
    obj   ORA_JAVA.JOBJECT,
    a0    NUMBER,
    a1    NUMBER);

  -- Method: wait ()V
  PROCEDURE wait(
    obj   ORA_JAVA.JOBJECT);

  -- Method: wait (J)V
  PROCEDURE wait(
    obj   ORA_JAVA.JOBJECT,
    a0    NUMBER);

  -- Method: notify ()V
  PROCEDURE notify(
    obj   ORA_JAVA.JOBJECT);

  -- Method: notifyAll ()V
  PROCEDURE notifyAll(
    obj   ORA_JAVA.JOBJECT);

END;
	*/
	
			//  
		//  DO NOT EDIT THIS FILE - it is machine generated!
		//  
		public NInteger separatorchar= NInteger.getNull();
		//  separatorChar
		public NString separator= NString.getNull();
		//  separator
		public NInteger pathseparatorchar= NInteger.getNull();
		//  pathSeparatorChar
		public NString pathseparator= NString.getNull();

			
		//Original PL/SQL code for Package Prog Unit (BODY) JAVA_FILE
		/*
		PACKAGE BODY JAVA_FILE IS

  -- 
  -- DO NOT EDIT THIS FILE - it is machine generated!
  -- 

  args   JNI.ARGLIST;

  -- Constructor for signature (Ljava/io/File;Ljava/lang/String;)V
  FUNCTION new(
    a0    ORA_JAVA.JOBJECT,
    a1    VARCHAR2) RETURN ORA_JAVA.JOBJECT IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(2);
    JNI.ADD_OBJECT_ARG(args, a0, 'java/io/File');
    JNI.ADD_STRING_ARG(args, a1);
    RETURN (JNI.NEW_OBJECT('java/io/File', '(Ljava/io/File;Ljava/lang/String;)V', args));
  END;

  -- Constructor for signature (Ljava/net/URI;)V
  FUNCTION new(
    a0    ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JOBJECT IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_OBJECT_ARG(args, a0, 'java/net/URI');
    RETURN (JNI.NEW_OBJECT('java/io/File', '(Ljava/net/URI;)V', args));
  END;

  -- Constructor for signature (Ljava/lang/String;)V
  FUNCTION new(
    a0    VARCHAR2) RETURN ORA_JAVA.JOBJECT IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_STRING_ARG(args, a0);
    RETURN (JNI.NEW_OBJECT('java/io/File', '(Ljava/lang/String;)V', args));
  END;

  -- Constructor for signature (Ljava/lang/String;Ljava/lang/String;)V
  FUNCTION new(
    a0    VARCHAR2,
    a1    VARCHAR2) RETURN ORA_JAVA.JOBJECT IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(2);
    JNI.ADD_STRING_ARG(args, a0);
    JNI.ADD_STRING_ARG(args, a1);
    RETURN (JNI.NEW_OBJECT('java/io/File', '(Ljava/lang/String;Ljava/lang/String;)V', args));
  END;

  -- Method: hashCode ()I
  FUNCTION hashCode(
    obj   ORA_JAVA.JOBJECT) RETURN NUMBER IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_INT_METHOD(FALSE, obj, 'java/io/File', 'hashCode', '()I', args); 
  END;

  -- Method: compareTo (Ljava/io/File;)I
  FUNCTION compareTo_0(
    obj   ORA_JAVA.JOBJECT,
    a0    ORA_JAVA.JOBJECT) RETURN NUMBER IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_OBJECT_ARG(args, a0, 'java/io/File');
    RETURN JNI.CALL_INT_METHOD(FALSE, obj, 'java/io/File', 'compareTo', '(Ljava/io/File;)I', args); 
  END;

  -- Method: compareTo (Ljava/lang/Object;)I
  FUNCTION compareTo_1(
    obj   ORA_JAVA.JOBJECT,
    a0    ORA_JAVA.JOBJECT) RETURN NUMBER IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_OBJECT_ARG(args, a0, 'java/lang/Object');
    RETURN JNI.CALL_INT_METHOD(FALSE, obj, 'java/io/File', 'compareTo', '(Ljava/lang/Object;)I', args); 
  END;

  -- Method: equals (Ljava/lang/Object;)Z
  FUNCTION equals(
    obj   ORA_JAVA.JOBJECT,
    a0    ORA_JAVA.JOBJECT) RETURN BOOLEAN IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_OBJECT_ARG(args, a0, 'java/lang/Object');
    RETURN JNI.CALL_BOOLEAN_METHOD(FALSE, obj, 'java/io/File', 'equals', '(Ljava/lang/Object;)Z', args); 
  END;

  -- Method: getName ()Ljava/lang/String;
  FUNCTION getName(
    obj   ORA_JAVA.JOBJECT) RETURN VARCHAR2 IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_STRING_METHOD(FALSE, obj, 'java/io/File', 'getName', '()Ljava/lang/String;', args); 
  END;

  -- Method: toString ()Ljava/lang/String;
  FUNCTION toString(
    obj   ORA_JAVA.JOBJECT) RETURN VARCHAR2 IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_STRING_METHOD(FALSE, obj, 'java/io/File', 'toString', '()Ljava/lang/String;', args); 
  END;

  -- Method: length ()J
  FUNCTION length(
    obj   ORA_JAVA.JOBJECT) RETURN NUMBER IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_LONG_METHOD(FALSE, obj, 'java/io/File', 'length', '()J', args); 
  END;

  -- Method: getCanonicalPath ()Ljava/lang/String;
  FUNCTION getCanonicalPath(
    obj   ORA_JAVA.JOBJECT) RETURN VARCHAR2 IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_STRING_METHOD(FALSE, obj, 'java/io/File', 'getCanonicalPath', '()Ljava/lang/String;', args); 
  END;

  -- Method: getParent ()Ljava/lang/String;
  FUNCTION getParent(
    obj   ORA_JAVA.JOBJECT) RETURN VARCHAR2 IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_STRING_METHOD(FALSE, obj, 'java/io/File', 'getParent', '()Ljava/lang/String;', args); 
  END;

  -- Method: isAbsolute ()Z
  FUNCTION isAbsolute(
    obj   ORA_JAVA.JOBJECT) RETURN BOOLEAN IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_BOOLEAN_METHOD(FALSE, obj, 'java/io/File', 'isAbsolute', '()Z', args); 
  END;

  -- Method: setReadOnly ()Z
  FUNCTION setReadOnly(
    obj   ORA_JAVA.JOBJECT) RETURN BOOLEAN IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_BOOLEAN_METHOD(FALSE, obj, 'java/io/File', 'setReadOnly', '()Z', args); 
  END;

  -- Method: list ()[Ljava/lang/String;
  FUNCTION list(
    obj   ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JARRAY IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_OBJECT_METHOD(FALSE, obj, 'java/io/File', 'list', '()[Ljava/lang/String;', args); 
  END;

  -- Method: list (Ljava/io/FilenameFilter;)[Ljava/lang/String;
  FUNCTION list(
    obj   ORA_JAVA.JOBJECT,
    a0    ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JARRAY IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_OBJECT_ARG(args, a0, 'java/io/FilenameFilter');
    RETURN JNI.CALL_OBJECT_METHOD(FALSE, obj, 'java/io/File', 'list', '(Ljava/io/FilenameFilter;)[Ljava/lang/String;', args); 
  END;

  -- Method: delete ()Z
  FUNCTION delete_(
    obj   ORA_JAVA.JOBJECT) RETURN BOOLEAN IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_BOOLEAN_METHOD(FALSE, obj, 'java/io/File', 'delete', '()Z', args); 
  END;

  -- Method: getPath ()Ljava/lang/String;
  FUNCTION getPath(
    obj   ORA_JAVA.JOBJECT) RETURN VARCHAR2 IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_STRING_METHOD(FALSE, obj, 'java/io/File', 'getPath', '()Ljava/lang/String;', args); 
  END;

  -- Method: canRead ()Z
  FUNCTION canRead(
    obj   ORA_JAVA.JOBJECT) RETURN BOOLEAN IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_BOOLEAN_METHOD(FALSE, obj, 'java/io/File', 'canRead', '()Z', args); 
  END;

  -- Method: canWrite ()Z
  FUNCTION canWrite(
    obj   ORA_JAVA.JOBJECT) RETURN BOOLEAN IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_BOOLEAN_METHOD(FALSE, obj, 'java/io/File', 'canWrite', '()Z', args); 
  END;

  -- Method: createNewFile ()Z
  FUNCTION createNewFile(
    obj   ORA_JAVA.JOBJECT) RETURN BOOLEAN IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_BOOLEAN_METHOD(FALSE, obj, 'java/io/File', 'createNewFile', '()Z', args); 
  END;

  -- Method: createTempFile (Ljava/lang/String;Ljava/lang/String;)Ljava/io/File;
  FUNCTION createTempFile(
    a0    VARCHAR2,
    a1    VARCHAR2) RETURN ORA_JAVA.JOBJECT IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(2);
    JNI.ADD_STRING_ARG(args, a0);
    JNI.ADD_STRING_ARG(args, a1);
    RETURN JNI.CALL_OBJECT_METHOD(TRUE, NULL, 'java/io/File', 'createTempFile', '(Ljava/lang/String;Ljava/lang/String;)Ljava/io/File;', args); 
  END;

  -- Method: createTempFile (Ljava/lang/String;Ljava/lang/String;Ljava/io/File;)Ljava/io/File;
  FUNCTION createTempFile(
    a0    VARCHAR2,
    a1    VARCHAR2,
    a2    ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JOBJECT IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(3);
    JNI.ADD_STRING_ARG(args, a0);
    JNI.ADD_STRING_ARG(args, a1);
    JNI.ADD_OBJECT_ARG(args, a2, 'java/io/File');
    RETURN JNI.CALL_OBJECT_METHOD(TRUE, NULL, 'java/io/File', 'createTempFile', '(Ljava/lang/String;Ljava/lang/String;Ljava/io/File;)Ljava/io/File;', args); 
  END;

  -- Method: deleteOnExit ()V
  PROCEDURE deleteOnExit(
    obj   ORA_JAVA.JOBJECT) IS
  BEGIN
    args := NULL;
    JNI.CALL_VOID_METHOD(FALSE, obj, 'java/io/File', 'deleteOnExit', '()V', args); 
  END;

  -- Method: exists ()Z
  FUNCTION exists_(
    obj   ORA_JAVA.JOBJECT) RETURN BOOLEAN IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_BOOLEAN_METHOD(FALSE, obj, 'java/io/File', 'exists', '()Z', args); 
  END;

  -- Method: getAbsoluteFile ()Ljava/io/File;
  FUNCTION getAbsoluteFile(
    obj   ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JOBJECT IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_OBJECT_METHOD(FALSE, obj, 'java/io/File', 'getAbsoluteFile', '()Ljava/io/File;', args); 
  END;

  -- Method: getAbsolutePath ()Ljava/lang/String;
  FUNCTION getAbsolutePath(
    obj   ORA_JAVA.JOBJECT) RETURN VARCHAR2 IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_STRING_METHOD(FALSE, obj, 'java/io/File', 'getAbsolutePath', '()Ljava/lang/String;', args); 
  END;

  -- Method: getCanonicalFile ()Ljava/io/File;
  FUNCTION getCanonicalFile(
    obj   ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JOBJECT IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_OBJECT_METHOD(FALSE, obj, 'java/io/File', 'getCanonicalFile', '()Ljava/io/File;', args); 
  END;

  -- Method: getParentFile ()Ljava/io/File;
  FUNCTION getParentFile(
    obj   ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JOBJECT IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_OBJECT_METHOD(FALSE, obj, 'java/io/File', 'getParentFile', '()Ljava/io/File;', args); 
  END;

  -- Method: isDirectory ()Z
  FUNCTION isDirectory(
    obj   ORA_JAVA.JOBJECT) RETURN BOOLEAN IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_BOOLEAN_METHOD(FALSE, obj, 'java/io/File', 'isDirectory', '()Z', args); 
  END;

  -- Method: isFile ()Z
  FUNCTION isFile(
    obj   ORA_JAVA.JOBJECT) RETURN BOOLEAN IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_BOOLEAN_METHOD(FALSE, obj, 'java/io/File', 'isFile', '()Z', args); 
  END;

  -- Method: isHidden ()Z
  FUNCTION isHidden(
    obj   ORA_JAVA.JOBJECT) RETURN BOOLEAN IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_BOOLEAN_METHOD(FALSE, obj, 'java/io/File', 'isHidden', '()Z', args); 
  END;

  -- Method: lastModified ()J
  FUNCTION lastModified(
    obj   ORA_JAVA.JOBJECT) RETURN NUMBER IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_LONG_METHOD(FALSE, obj, 'java/io/File', 'lastModified', '()J', args); 
  END;

  -- Method: listFiles (Ljava/io/FileFilter;)[Ljava/io/File;
  FUNCTION listFiles_0(
    obj   ORA_JAVA.JOBJECT,
    a0    ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JARRAY IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_OBJECT_ARG(args, a0, 'java/io/FileFilter');
    RETURN JNI.CALL_OBJECT_METHOD(FALSE, obj, 'java/io/File', 'listFiles', '(Ljava/io/FileFilter;)[Ljava/io/File;', args); 
  END;

  -- Method: listFiles (Ljava/io/FilenameFilter;)[Ljava/io/File;
  FUNCTION listFiles_1(
    obj   ORA_JAVA.JOBJECT,
    a0    ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JARRAY IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_OBJECT_ARG(args, a0, 'java/io/FilenameFilter');
    RETURN JNI.CALL_OBJECT_METHOD(FALSE, obj, 'java/io/File', 'listFiles', '(Ljava/io/FilenameFilter;)[Ljava/io/File;', args); 
  END;

  -- Method: listFiles ()[Ljava/io/File;
  FUNCTION listFiles(
    obj   ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JARRAY IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_OBJECT_METHOD(FALSE, obj, 'java/io/File', 'listFiles', '()[Ljava/io/File;', args); 
  END;

  -- Method: listRoots ()[Ljava/io/File;
  FUNCTION listRoots RETURN ORA_JAVA.JARRAY IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_OBJECT_METHOD(TRUE, NULL, 'java/io/File', 'listRoots', '()[Ljava/io/File;', args); 
  END;

  -- Method: mkdir ()Z
  FUNCTION mkdir(
    obj   ORA_JAVA.JOBJECT) RETURN BOOLEAN IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_BOOLEAN_METHOD(FALSE, obj, 'java/io/File', 'mkdir', '()Z', args); 
  END;

  -- Method: mkdirs ()Z
  FUNCTION mkdirs(
    obj   ORA_JAVA.JOBJECT) RETURN BOOLEAN IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_BOOLEAN_METHOD(FALSE, obj, 'java/io/File', 'mkdirs', '()Z', args); 
  END;

  -- Method: renameTo (Ljava/io/File;)Z
  FUNCTION renameTo(
    obj   ORA_JAVA.JOBJECT,
    a0    ORA_JAVA.JOBJECT) RETURN BOOLEAN IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_OBJECT_ARG(args, a0, 'java/io/File');
    RETURN JNI.CALL_BOOLEAN_METHOD(FALSE, obj, 'java/io/File', 'renameTo', '(Ljava/io/File;)Z', args); 
  END;

  -- Method: setLastModified (J)Z
  FUNCTION setLastModified(
    obj   ORA_JAVA.JOBJECT,
    a0    NUMBER) RETURN BOOLEAN IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_LONG_ARG(args, a0);
    RETURN JNI.CALL_BOOLEAN_METHOD(FALSE, obj, 'java/io/File', 'setLastModified', '(J)Z', args); 
  END;

  -- Method: toURI ()Ljava/net/URI;
  FUNCTION toURI(
    obj   ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JOBJECT IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_OBJECT_METHOD(FALSE, obj, 'java/io/File', 'toURI', '()Ljava/net/URI;', args); 
  END;

  -- Method: toURL ()Ljava/net/URL;
  FUNCTION toURL(
    obj   ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JOBJECT IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_OBJECT_METHOD(FALSE, obj, 'java/io/File', 'toURL', '()Ljava/net/URL;', args); 
  END;

  -- Method: getClass ()Ljava/lang/Class;
  FUNCTION getClass(
    obj   ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JOBJECT IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_OBJECT_METHOD(FALSE, obj, 'java/io/File', 'getClass', '()Ljava/lang/Class;', args); 
  END;

  -- Method: wait (JI)V
  PROCEDURE wait(
    obj   ORA_JAVA.JOBJECT,
    a0    NUMBER,
    a1    NUMBER) IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(2);
    JNI.ADD_LONG_ARG(args, a0);
    JNI.ADD_INT_ARG(args, a1);
    JNI.CALL_VOID_METHOD(FALSE, obj, 'java/io/File', 'wait', '(JI)V', args); 
  END;

  -- Method: wait ()V
  PROCEDURE wait(
    obj   ORA_JAVA.JOBJECT) IS
  BEGIN
    args := NULL;
    JNI.CALL_VOID_METHOD(FALSE, obj, 'java/io/File', 'wait', '()V', args); 
  END;

  -- Method: wait (J)V
  PROCEDURE wait(
    obj   ORA_JAVA.JOBJECT,
    a0    NUMBER) IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_LONG_ARG(args, a0);
    JNI.CALL_VOID_METHOD(FALSE, obj, 'java/io/File', 'wait', '(J)V', args); 
  END;

  -- Method: notify ()V
  PROCEDURE notify(
    obj   ORA_JAVA.JOBJECT) IS
  BEGIN
    args := NULL;
    JNI.CALL_VOID_METHOD(FALSE, obj, 'java/io/File', 'notify', '()V', args); 
  END;

  -- Method: notifyAll ()V
  PROCEDURE notifyAll(
    obj   ORA_JAVA.JOBJECT) IS
  BEGIN
    args := NULL;
    JNI.CALL_VOID_METHOD(FALSE, obj, 'java/io/File', 'notifyAll', '()V', args); 
  END;


BEGIN
  -- separatorChar (C)
  separatorChar := JNI.GET_CHAR_FIELD(TRUE, NULL, 'java/io/File', 'separatorChar', 'C');

  -- separator (Ljava/lang/String;)
  separator := JNI.GET_STRING_FIELD(TRUE, NULL, 'java/io/File', 'separator', 'Ljava/lang/String;');

  -- pathSeparatorChar (C)
  pathSeparatorChar := JNI.GET_CHAR_FIELD(TRUE, NULL, 'java/io/File', 'pathSeparatorChar', 'C');

  -- pathSeparator (Ljava/lang/String;)
  pathSeparator := JNI.GET_STRING_FIELD(TRUE, NULL, 'java/io/File', 'pathSeparator', 'Ljava/lang/String;');

END;
		*/
				//  
		//  DO NOT EDIT THIS FILE - it is machine generated!
		//  
		private UnknownTypes.JniArglist args= null;
/* <p>
		*  Constructor for signature (Ljava/io/File;Ljava/lang/String;)V
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param a0
		* @param a1
		*/
		public UnknownTypes.OraJavaJobject _new(UnknownTypes.OraJavaJobject a0, NString a1)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(2);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_OBJECT_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6".
//			//			SupportClasses.JNI.AddObjectArg(args, a0, "java/io/File");
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_OBJECT_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_STRING_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10".
//			//			SupportClasses.JNI.AddStringArg(args, a1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_STRING_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10'.");
//			
//			return ((SupportClasses.JNI.NewObject("java/io/File", "(Ljava/io/File;Ljava/lang/String;)V", args)));
//
			this.getLogger().trace(this, "F2J : _new function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return null;
		}
/* <p>
		*  Constructor for signature (Ljava/net/URI;)V
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param a0
		*/
		public UnknownTypes.OraJavaJobject _new(UnknownTypes.OraJavaJobject a0)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_OBJECT_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6".
//			//			SupportClasses.JNI.AddObjectArg(args, a0, "java/net/URI");
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_OBJECT_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6'.");
//			
//			return ((SupportClasses.JNI.NewObject("java/io/File", "(Ljava/net/URI;)V", args)));
//
			this.getLogger().trace(this, "F2J : _new function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return null;
		}
/* <p>
		*  Constructor for signature (Ljava/lang/String;)V
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param a0
		*/
		public UnknownTypes.OraJavaJobject _new(NString a0)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_STRING_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10".
//			//			SupportClasses.JNI.AddStringArg(args, a0);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_STRING_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10'.");
//			
//			return ((SupportClasses.JNI.NewObject("java/io/File", "(Ljava/lang/String;)V", args)));
//
			this.getLogger().trace(this, "F2J : _new function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return null;
		}
/* <p>
		*  Constructor for signature (Ljava/lang/String;Ljava/lang/String;)V
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param a0
		* @param a1
		*/
		public UnknownTypes.OraJavaJobject _new(NString a0, NString a1)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(2);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_STRING_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10".
//			//			SupportClasses.JNI.AddStringArg(args, a0);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_STRING_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_STRING_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10".
//			//			SupportClasses.JNI.AddStringArg(args, a1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_STRING_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10'.");
//			
//			return ((SupportClasses.JNI.NewObject("java/io/File", "(Ljava/lang/String;Ljava/lang/String;)V", args)));
//
			this.getLogger().trace(this, "F2J : _new function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return null;
		}
/* <p>
		*  Method: hashCode ()I
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public NNumber hashcode(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallIntMethod(NBool.False, obj, "java/io/File", "hashCode", "()I", args);
//
			this.getLogger().trace(this, "F2J : hashcode function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NNumber.getNull();
		}
/* <p>
		*  Method: compareTo (Ljava/io/File;)I
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		* @param a0
		*/
		public NNumber compareto0(UnknownTypes.OraJavaJobject obj, UnknownTypes.OraJavaJobject a0)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_OBJECT_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6".
//			//			SupportClasses.JNI.AddObjectArg(args, a0, "java/io/File");
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_OBJECT_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6'.");
//			
//			return SupportClasses.JNI.CallIntMethod(NBool.False, obj, "java/io/File", "compareTo", "(Ljava/io/File;)I", args);
//
			this.getLogger().trace(this, "F2J : compareto0 function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NNumber.getNull();
		}
/* <p>
		*  Method: compareTo (Ljava/lang/Object;)I
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		* @param a0
		*/
		public NNumber compareto1(UnknownTypes.OraJavaJobject obj, UnknownTypes.OraJavaJobject a0)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_OBJECT_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6".
//			//			SupportClasses.JNI.AddObjectArg(args, a0, "java/lang/Object");
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_OBJECT_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6'.");
//			
//			return SupportClasses.JNI.CallIntMethod(NBool.False, obj, "java/io/File", "compareTo", "(Ljava/lang/Object;)I", args);
//
			this.getLogger().trace(this, "F2J : compareto1 function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NNumber.getNull();
		}
/* <p>
		*  Method: equals (Ljava/lang/Object;)Z
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		* @param a0
		*/
		public NBool equals(UnknownTypes.OraJavaJobject obj, UnknownTypes.OraJavaJobject a0)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_OBJECT_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6".
//			//			SupportClasses.JNI.AddObjectArg(args, a0, "java/lang/Object");
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_OBJECT_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6'.");
//			
//			return SupportClasses.JNI.CallBooleanMethod(NBool.False, obj, "java/io/File", "equals", "(Ljava/lang/Object;)Z", args);
//
			this.getLogger().trace(this, "F2J : equals function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NBool.getNull();
		}
/* <p>
		*  Method: getName ()Ljava/lang/String;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public NString getname(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallStringMethod(NBool.False, obj, "java/io/File", "getName", "()Ljava/lang/String;", args);
//
			this.getLogger().trace(this, "F2J : getname function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NString.getNull();
		}
/* <p>
		*  Method: toString ()Ljava/lang/String;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public NString tostring(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallStringMethod(NBool.False, obj, "java/io/File", "toString", "()Ljava/lang/String;", args);
//
			this.getLogger().trace(this, "F2J : tostring function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NString.getNull();
		}
/* <p>
		*  Method: length ()J
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public NNumber length(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallLongMethod(NBool.False, obj, "java/io/File", "length", "()J", args);
//
			this.getLogger().trace(this, "F2J : length function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NNumber.getNull();
		}
/* <p>
		*  Method: getCanonicalPath ()Ljava/lang/String;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public NString getcanonicalpath(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallStringMethod(NBool.False, obj, "java/io/File", "getCanonicalPath", "()Ljava/lang/String;", args);
//
			this.getLogger().trace(this, "F2J : getcanonicalpath function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NString.getNull();
		}
/* <p>
		*  Method: getParent ()Ljava/lang/String;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public NString getparent(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallStringMethod(NBool.False, obj, "java/io/File", "getParent", "()Ljava/lang/String;", args);
//
			this.getLogger().trace(this, "F2J : getparent function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NString.getNull();
		}
/* <p>
		*  Method: isAbsolute ()Z
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public NBool isabsolute(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallBooleanMethod(NBool.False, obj, "java/io/File", "isAbsolute", "()Z", args);
//
			this.getLogger().trace(this, "F2J : isabsolute function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NBool.getNull();
		}
/* <p>
		*  Method: setReadOnly ()Z
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public NBool setreadonly(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallBooleanMethod(NBool.False, obj, "java/io/File", "setReadOnly", "()Z", args);
//
			this.getLogger().trace(this, "F2J : setreadonly function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NBool.getNull();
		}
/* <p>
		*  Method: list ()[Ljava/lang/String;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public UnknownTypes.OraJavaJarray list(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallObjectMethod(NBool.False, obj, "java/io/File", "list", "()[Ljava/lang/String;", args);
//
			this.getLogger().trace(this, "F2J : list function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return null;
		}
/* <p>
		*  Method: list (Ljava/io/FilenameFilter;)[Ljava/lang/String;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		* @param a0
		*/
		public UnknownTypes.OraJavaJarray list(UnknownTypes.OraJavaJobject obj, UnknownTypes.OraJavaJobject a0)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_OBJECT_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6".
//			//			SupportClasses.JNI.AddObjectArg(args, a0, "java/io/FilenameFilter");
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_OBJECT_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6'.");
//			
//			return SupportClasses.JNI.CallObjectMethod(NBool.False, obj, "java/io/File", "list", "(Ljava/io/FilenameFilter;)[Ljava/lang/String;", args);
//
			this.getLogger().trace(this, "F2J : list function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return null;
		}
/* <p>
		*  Method: delete ()Z
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public NBool delete_(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallBooleanMethod(NBool.False, obj, "java/io/File", "delete", "()Z", args);
//
			this.getLogger().trace(this, "F2J : delete_ function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NBool.getNull();
		}
/* <p>
		*  Method: getPath ()Ljava/lang/String;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public NString getpath(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallStringMethod(NBool.False, obj, "java/io/File", "getPath", "()Ljava/lang/String;", args);
//
			this.getLogger().trace(this, "F2J : getpath function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NString.getNull();
		}
/* <p>
		*  Method: canRead ()Z
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public NBool canread(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallBooleanMethod(NBool.False, obj, "java/io/File", "canRead", "()Z", args);
//
			this.getLogger().trace(this, "F2J : canread function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NBool.getNull();
		}
/* <p>
		*  Method: canWrite ()Z
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public NBool canwrite(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallBooleanMethod(NBool.False, obj, "java/io/File", "canWrite", "()Z", args);
//
			this.getLogger().trace(this, "F2J : canwrite function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NBool.getNull();
		}
/* <p>
		*  Method: createNewFile ()Z
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public NBool createnewfile(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallBooleanMethod(NBool.False, obj, "java/io/File", "createNewFile", "()Z", args);
//
			this.getLogger().trace(this, "F2J : createnewfile function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NBool.getNull();
		}
/* <p>
		*  Method: createTempFile (Ljava/lang/String;Ljava/lang/String;)Ljava/io/File;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param a0
		* @param a1
		*/
		public UnknownTypes.OraJavaJobject createtempfile(NString a0, NString a1)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(2);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_STRING_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10".
//			//			SupportClasses.JNI.AddStringArg(args, a0);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_STRING_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_STRING_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10".
//			//			SupportClasses.JNI.AddStringArg(args, a1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_STRING_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10'.");
//			
//			return SupportClasses.JNI.CallObjectMethod(NBool.True, null, "java/io/File", "createTempFile", "(Ljava/lang/String;Ljava/lang/String;)Ljava/io/File;", args);
//
			this.getLogger().trace(this, "F2J : createtempfile function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return null;
		}
/* <p>
		*  Method: createTempFile (Ljava/lang/String;Ljava/lang/String;Ljava/io/File;)Ljava/io/File;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param a0
		* @param a1
		* @param a2
		*/
		public UnknownTypes.OraJavaJobject createtempfile(NString a0, NString a1, UnknownTypes.OraJavaJobject a2)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(3);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_STRING_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10".
//			//			SupportClasses.JNI.AddStringArg(args, a0);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_STRING_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_STRING_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10".
//			//			SupportClasses.JNI.AddStringArg(args, a1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_STRING_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_OBJECT_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6".
//			//			SupportClasses.JNI.AddObjectArg(args, a2, "java/io/File");
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_OBJECT_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6'.");
//			
//			return SupportClasses.JNI.CallObjectMethod(NBool.True, null, "java/io/File", "createTempFile", "(Ljava/lang/String;Ljava/lang/String;Ljava/io/File;)Ljava/io/File;", args);
//
			this.getLogger().trace(this, "F2J : createtempfile function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return null;
		}
/* <p>
		*  Method: deleteOnExit ()V
		* F2J_PURE_BUSINESS_LOGIC : The code of this procedure was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public void deleteonexit(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Procedure was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			// F2J_NOT_SUPPORTED : Call to built-in "CALL_VOID_METHOD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8".
//			//			SupportClasses.JNI.CallVoidMethod(NBool.False, obj, "java/io/File", "deleteOnExit", "()V", args);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CALL_VOID_METHOD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8'.");
//			
//
			this.getLogger().trace(this, "F2J : deleteonexit procedure is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
/* <p>
		*  Method: exists ()Z
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public NBool exists_(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallBooleanMethod(NBool.False, obj, "java/io/File", "exists", "()Z", args);
//
			this.getLogger().trace(this, "F2J : exists_ function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NBool.getNull();
		}
/* <p>
		*  Method: getAbsoluteFile ()Ljava/io/File;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public UnknownTypes.OraJavaJobject getabsolutefile(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallObjectMethod(NBool.False, obj, "java/io/File", "getAbsoluteFile", "()Ljava/io/File;", args);
//
			this.getLogger().trace(this, "F2J : getabsolutefile function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return null;
		}
/* <p>
		*  Method: getAbsolutePath ()Ljava/lang/String;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public NString getabsolutepath(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallStringMethod(NBool.False, obj, "java/io/File", "getAbsolutePath", "()Ljava/lang/String;", args);
//
			this.getLogger().trace(this, "F2J : getabsolutepath function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NString.getNull();
		}
/* <p>
		*  Method: getCanonicalFile ()Ljava/io/File;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public UnknownTypes.OraJavaJobject getcanonicalfile(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallObjectMethod(NBool.False, obj, "java/io/File", "getCanonicalFile", "()Ljava/io/File;", args);
//
			this.getLogger().trace(this, "F2J : getcanonicalfile function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return null;
		}
/* <p>
		*  Method: getParentFile ()Ljava/io/File;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public UnknownTypes.OraJavaJobject getparentfile(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallObjectMethod(NBool.False, obj, "java/io/File", "getParentFile", "()Ljava/io/File;", args);
//
			this.getLogger().trace(this, "F2J : getparentfile function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return null;
		}
/* <p>
		*  Method: isDirectory ()Z
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public NBool isdirectory(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallBooleanMethod(NBool.False, obj, "java/io/File", "isDirectory", "()Z", args);
//
			this.getLogger().trace(this, "F2J : isdirectory function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NBool.getNull();
		}
/* <p>
		*  Method: isFile ()Z
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public NBool isfile(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallBooleanMethod(NBool.False, obj, "java/io/File", "isFile", "()Z", args);
//
			this.getLogger().trace(this, "F2J : isfile function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NBool.getNull();
		}
/* <p>
		*  Method: isHidden ()Z
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public NBool ishidden(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallBooleanMethod(NBool.False, obj, "java/io/File", "isHidden", "()Z", args);
//
			this.getLogger().trace(this, "F2J : ishidden function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NBool.getNull();
		}
/* <p>
		*  Method: lastModified ()J
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public NNumber lastmodified(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallLongMethod(NBool.False, obj, "java/io/File", "lastModified", "()J", args);
//
			this.getLogger().trace(this, "F2J : lastmodified function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NNumber.getNull();
		}
/* <p>
		*  Method: listFiles (Ljava/io/FileFilter;)[Ljava/io/File;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		* @param a0
		*/
		public UnknownTypes.OraJavaJarray listfiles0(UnknownTypes.OraJavaJobject obj, UnknownTypes.OraJavaJobject a0)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_OBJECT_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6".
//			//			SupportClasses.JNI.AddObjectArg(args, a0, "java/io/FileFilter");
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_OBJECT_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6'.");
//			
//			return SupportClasses.JNI.CallObjectMethod(NBool.False, obj, "java/io/File", "listFiles", "(Ljava/io/FileFilter;)[Ljava/io/File;", args);
//
			this.getLogger().trace(this, "F2J : listfiles0 function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return null;
		}
/* <p>
		*  Method: listFiles (Ljava/io/FilenameFilter;)[Ljava/io/File;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		* @param a0
		*/
		public UnknownTypes.OraJavaJarray listfiles1(UnknownTypes.OraJavaJobject obj, UnknownTypes.OraJavaJobject a0)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_OBJECT_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6".
//			//			SupportClasses.JNI.AddObjectArg(args, a0, "java/io/FilenameFilter");
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_OBJECT_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6'.");
//			
//			return SupportClasses.JNI.CallObjectMethod(NBool.False, obj, "java/io/File", "listFiles", "(Ljava/io/FilenameFilter;)[Ljava/io/File;", args);
//
			this.getLogger().trace(this, "F2J : listfiles1 function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return null;
		}
/* <p>
		*  Method: listFiles ()[Ljava/io/File;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public UnknownTypes.OraJavaJarray listfiles(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallObjectMethod(NBool.False, obj, "java/io/File", "listFiles", "()[Ljava/io/File;", args);
//
			this.getLogger().trace(this, "F2J : listfiles function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return null;
		}
/* <p>
		*  Method: listRoots ()[Ljava/io/File;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		*/
		public UnknownTypes.OraJavaJarray listroots()
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallObjectMethod(NBool.True, null, "java/io/File", "listRoots", "()[Ljava/io/File;", args);
//
			this.getLogger().trace(this, "F2J : listroots function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return null;
		}
/* <p>
		*  Method: mkdir ()Z
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public NBool mkdir(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallBooleanMethod(NBool.False, obj, "java/io/File", "mkdir", "()Z", args);
//
			this.getLogger().trace(this, "F2J : mkdir function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NBool.getNull();
		}
/* <p>
		*  Method: mkdirs ()Z
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public NBool mkdirs(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallBooleanMethod(NBool.False, obj, "java/io/File", "mkdirs", "()Z", args);
//
			this.getLogger().trace(this, "F2J : mkdirs function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NBool.getNull();
		}
/* <p>
		*  Method: renameTo (Ljava/io/File;)Z
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		* @param a0
		*/
		public NBool renameto(UnknownTypes.OraJavaJobject obj, UnknownTypes.OraJavaJobject a0)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_OBJECT_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6".
//			//			SupportClasses.JNI.AddObjectArg(args, a0, "java/io/File");
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_OBJECT_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6'.");
//			
//			return SupportClasses.JNI.CallBooleanMethod(NBool.False, obj, "java/io/File", "renameTo", "(Ljava/io/File;)Z", args);
//
			this.getLogger().trace(this, "F2J : renameto function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NBool.getNull();
		}
/* <p>
		*  Method: setLastModified (J)Z
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		* @param a0
		*/
		public NBool setlastmodified(UnknownTypes.OraJavaJobject obj, NNumber a0)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_LONG_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin11".
//			//			SupportClasses.JNI.AddLongArg(args, a0);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_LONG_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin11'.");
//			
//			return SupportClasses.JNI.CallBooleanMethod(NBool.False, obj, "java/io/File", "setLastModified", "(J)Z", args);
//
			this.getLogger().trace(this, "F2J : setlastmodified function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NBool.getNull();
		}
/* <p>
		*  Method: toURI ()Ljava/net/URI;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public UnknownTypes.OraJavaJobject touri(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallObjectMethod(NBool.False, obj, "java/io/File", "toURI", "()Ljava/net/URI;", args);
//
			this.getLogger().trace(this, "F2J : touri function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return null;
		}
/* <p>
		*  Method: toURL ()Ljava/net/URL;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public UnknownTypes.OraJavaJobject tourl(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallObjectMethod(NBool.False, obj, "java/io/File", "toURL", "()Ljava/net/URL;", args);
//
			this.getLogger().trace(this, "F2J : tourl function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return null;
		}
/* <p>
		*  Method: getClass ()Ljava/lang/Class;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public UnknownTypes.OraJavaJobject getclass(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallObjectMethod(NBool.False, obj, "java/io/File", "getClass", "()Ljava/lang/Class;", args);
//
			this.getLogger().trace(this, "F2J : getclass function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return null;
		}
/* <p>
		*  Method: wait (JI)V
		* F2J_PURE_BUSINESS_LOGIC : The code of this procedure was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		* @param a0
		* @param a1
		*/
		public void wait(UnknownTypes.OraJavaJobject obj, NNumber a0, NNumber a1)
		{
			//F2J_WRAPPED_CODE : The code of this Procedure was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(2);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_LONG_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin11".
//			//			SupportClasses.JNI.AddLongArg(args, a0);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_LONG_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin11'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_INT_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin7".
//			//			SupportClasses.JNI.AddIntArg(args, a1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_INT_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin7'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "CALL_VOID_METHOD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8".
//			//			SupportClasses.JNI.CallVoidMethod(NBool.False, obj, "java/io/File", "wait", "(JI)V", args);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CALL_VOID_METHOD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8'.");
//			
//
			this.getLogger().trace(this, "F2J : wait procedure is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
/* <p>
		*  Method: wait ()V
		* F2J_PURE_BUSINESS_LOGIC : The code of this procedure was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public void wait(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Procedure was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			// F2J_NOT_SUPPORTED : Call to built-in "CALL_VOID_METHOD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8".
//			//			SupportClasses.JNI.CallVoidMethod(NBool.False, obj, "java/io/File", "wait", "()V", args);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CALL_VOID_METHOD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8'.");
//			
//
			this.getLogger().trace(this, "F2J : wait procedure is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
/* <p>
		*  Method: wait (J)V
		* F2J_PURE_BUSINESS_LOGIC : The code of this procedure was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		* @param a0
		*/
		public void wait(UnknownTypes.OraJavaJobject obj, NNumber a0)
		{
			//F2J_WRAPPED_CODE : The code of this Procedure was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_LONG_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin11".
//			//			SupportClasses.JNI.AddLongArg(args, a0);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_LONG_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin11'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "CALL_VOID_METHOD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8".
//			//			SupportClasses.JNI.CallVoidMethod(NBool.False, obj, "java/io/File", "wait", "(J)V", args);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CALL_VOID_METHOD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8'.");
//			
//
			this.getLogger().trace(this, "F2J : wait procedure is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
/* <p>
		*  Method: notify ()V
		* F2J_PURE_BUSINESS_LOGIC : The code of this procedure was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public void notify(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Procedure was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			// F2J_NOT_SUPPORTED : Call to built-in "CALL_VOID_METHOD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8".
//			//			SupportClasses.JNI.CallVoidMethod(NBool.False, obj, "java/io/File", "notify", "()V", args);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CALL_VOID_METHOD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8'.");
//			
//
			this.getLogger().trace(this, "F2J : notify procedure is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
/* <p>
		*  Method: notifyAll ()V
		* F2J_PURE_BUSINESS_LOGIC : The code of this procedure was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public void notifyall(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Procedure was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			// F2J_NOT_SUPPORTED : Call to built-in "CALL_VOID_METHOD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8".
//			//			SupportClasses.JNI.CallVoidMethod(NBool.False, obj, "java/io/File", "notifyAll", "()V", args);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CALL_VOID_METHOD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8'.");
//			
//
			this.getLogger().trace(this, "F2J : notifyall procedure is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
		public JavaFile() {
			//F2J_WRAPPED_CODE : The code of this Package Constructor was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			//  separatorChar (C)
//			// F2J_NOT_SUPPORTED : Call to built-in "GET_CHAR_FIELD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin13".
//			//			separatorchar = SupportClasses.JNI.GetCharField(NBool.True, null, "java/io/File", "separatorChar", "C");
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'GET_CHAR_FIELD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin13'.");
//			
//			//  separator (Ljava/lang/String;)
//			// F2J_NOT_SUPPORTED : Call to built-in "GET_STRING_FIELD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin14".
//			//			separator = SupportClasses.JNI.GetStringField(NBool.True, null, "java/io/File", "separator", "Ljava/lang/String;");
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'GET_STRING_FIELD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin14'.");
//			
//			//  pathSeparatorChar (C)
//			// F2J_NOT_SUPPORTED : Call to built-in "GET_CHAR_FIELD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin13".
//			//			pathseparatorchar = SupportClasses.JNI.GetCharField(NBool.True, null, "java/io/File", "pathSeparatorChar", "C");
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'GET_CHAR_FIELD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin13'.");
//			
//			//  pathSeparator (Ljava/lang/String;)
//			// F2J_NOT_SUPPORTED : Call to built-in "GET_STRING_FIELD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin14".
//			//			pathseparator = SupportClasses.JNI.GetStringField(NBool.True, null, "java/io/File", "pathSeparator", "Ljava/lang/String;");
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'GET_STRING_FIELD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin14'.");
//			
//
			this.getLogger().trace(this, "F2J : JavaFile Constructor is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
		
	
	
}
