package net.hedtech.general.common.libraries.Webutil;

import java.util.*;
import org.jdesktop.databuffer.DataRow.DataRowStatus;

import morphis.foundations.core.appdatalayer.*;
import morphis.foundations.core.appdatalayer.data.*;
import morphis.foundations.core.types.*;
import morphis.foundations.core.appsupportlib.*;
import morphis.foundations.core.appsupportlib.exceptions.*;
import morphis.foundations.core.appsupportlib.model.*;
import morphis.foundations.core.appsupportlib.util.*;
import morphis.foundations.core.appsupportlib.runtime.*;
import morphis.foundations.core.appsupportlib.runtime.controlsModel.items.*;
import morphis.foundations.core.appsupportlib.runtime.controlsModel.lovs.*;
import morphis.foundations.core.appsupportlib.runtime.controlsModel.containers.*;
import morphis.foundations.core.appsupportlib.runtime.controlsModel.alerts.*;
import static morphis.foundations.core.appsupportlib.runtime.TaskServices.*;
import static morphis.foundations.core.appsupportlib.runtime.ItemServices.*;
import static morphis.foundations.core.appsupportlib.runtime.BlockServices.*;
import static morphis.foundations.core.appsupportlib.runtime.ViewServices.*;
import static morphis.foundations.core.appsupportlib.runtime.MessageServices.*;
import static morphis.foundations.core.appsupportlib.runtime.ValueSetServices.*;
import static morphis.foundations.core.appsupportlib.runtime.LovServices.*;
import static morphis.foundations.core.appsupportlib.Math.*;
import static morphis.foundations.core.appsupportlib.Lib.*;
import static morphis.foundations.core.appsupportlib.Globals.*;
import static morphis.foundations.core.types.Types.*;
import morphis.foundations.core.util.*;

import net.hedtech.general.common.dbservices.*;
import net.hedtech.general.common.dbservices.dbtypes.*;


public class JavaSystem extends AbstractSupportCodeObject {
	

	public JavaSystem(ISupportCodeContainer container) {
		super(container);
	}
	
	@Override
	public WebutilServices getContainer() {
		return (WebutilServices)super.getContainer();
	}
	//Original PL/SQL code for Package Prog Unit (SPEC) JAVA_SYSTEM
	/*
	PACKAGE JAVA_SYSTEM <multilinecomment> java.lang.System </multilinecomment> IS

  -- 
  -- DO NOT EDIT THIS FILE - it is machine generated!
  -- 
  in_  ORA_JAVA.JOBJECT;  -- in
  out_  ORA_JAVA.JOBJECT;  -- out
  err  ORA_JAVA.JOBJECT;  -- err


  -- Method: arraycopy (Ljava/lang/Object;ILjava/lang/Object;II)V
  PROCEDURE arraycopy(
    a0    ORA_JAVA.JOBJECT,
    a1    NUMBER,
    a2    ORA_JAVA.JOBJECT,
    a3    NUMBER,
    a4    NUMBER);

  -- Method: currentTimeMillis ()J
  FUNCTION currentTimeMillis RETURN NUMBER;

  -- Method: identityHashCode (Ljava/lang/Object;)I
  FUNCTION identityHashCode(
    a0    ORA_JAVA.JOBJECT) RETURN NUMBER;

  -- Method: exit (I)V
  PROCEDURE exit_(
    a0    NUMBER);

  -- Method: runFinalizersOnExit (Z)V
  PROCEDURE runFinalizersOnExit(
    a0    BOOLEAN);

  -- Method: setProperty (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
  FUNCTION setProperty(
    a0    VARCHAR2,
    a1    VARCHAR2) RETURN VARCHAR2;

  -- Method: getProperty (Ljava/lang/String;)Ljava/lang/String;
  FUNCTION getProperty(
    a0    VARCHAR2) RETURN VARCHAR2;

  -- Method: getProperty (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
  FUNCTION getProperty(
    a0    VARCHAR2,
    a1    VARCHAR2) RETURN VARCHAR2;

  -- Method: getSecurityManager ()Ljava/lang/SecurityManager;
  FUNCTION getSecurityManager RETURN ORA_JAVA.JOBJECT;

  -- Method: load (Ljava/lang/String;)V
  PROCEDURE load(
    a0    VARCHAR2);

  -- Method: loadLibrary (Ljava/lang/String;)V
  PROCEDURE loadLibrary(
    a0    VARCHAR2);

  -- Method: mapLibraryName (Ljava/lang/String;)Ljava/lang/String;
  FUNCTION mapLibraryName(
    a0    VARCHAR2) RETURN VARCHAR2;

  -- Method: gc ()V
  PROCEDURE gc;

  -- Method: getProperties ()Ljava/util/Properties;
  FUNCTION getProperties RETURN ORA_JAVA.JOBJECT;

  -- Method: getenv (Ljava/lang/String;)Ljava/lang/String;
  FUNCTION getenv(
    a0    VARCHAR2) RETURN VARCHAR2;

  -- Method: runFinalization ()V
  PROCEDURE runFinalization;

  -- Method: setErr (Ljava/io/PrintStream;)V
  PROCEDURE setErr(
    a0    ORA_JAVA.JOBJECT);

  -- Method: setIn (Ljava/io/InputStream;)V
  PROCEDURE setIn(
    a0    ORA_JAVA.JOBJECT);

  -- Method: setOut (Ljava/io/PrintStream;)V
  PROCEDURE setOut(
    a0    ORA_JAVA.JOBJECT);

  -- Method: setProperties (Ljava/util/Properties;)V
  PROCEDURE setProperties(
    a0    ORA_JAVA.JOBJECT);

  -- Method: setSecurityManager (Ljava/lang/SecurityManager;)V
  PROCEDURE setSecurityManager(
    a0    ORA_JAVA.JOBJECT);

  -- Method: hashCode ()I
  FUNCTION hashCode(
    obj   ORA_JAVA.JOBJECT) RETURN NUMBER;

  -- Method: getClass ()Ljava/lang/Class;
  FUNCTION getClass(
    obj   ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JOBJECT;

  -- Method: wait (JI)V
  PROCEDURE wait(
    obj   ORA_JAVA.JOBJECT,
    a0    NUMBER,
    a1    NUMBER);

  -- Method: wait ()V
  PROCEDURE wait(
    obj   ORA_JAVA.JOBJECT);

  -- Method: wait (J)V
  PROCEDURE wait(
    obj   ORA_JAVA.JOBJECT,
    a0    NUMBER);

  -- Method: equals (Ljava/lang/Object;)Z
  FUNCTION equals(
    obj   ORA_JAVA.JOBJECT,
    a0    ORA_JAVA.JOBJECT) RETURN BOOLEAN;

  -- Method: notify ()V
  PROCEDURE notify(
    obj   ORA_JAVA.JOBJECT);

  -- Method: notifyAll ()V
  PROCEDURE notifyAll(
    obj   ORA_JAVA.JOBJECT);

  -- Method: toString ()Ljava/lang/String;
  FUNCTION toString(
    obj   ORA_JAVA.JOBJECT) RETURN VARCHAR2;

END;
	*/
	
			//  
		//  DO NOT EDIT THIS FILE - it is machine generated!
		//  
		public UnknownTypes.OraJavaJobject in_= null;
		//  in
		public UnknownTypes.OraJavaJobject out_= null;
		//  out
		public UnknownTypes.OraJavaJobject err= null;

			
		//Original PL/SQL code for Package Prog Unit (BODY) JAVA_SYSTEM
		/*
		PACKAGE BODY JAVA_SYSTEM IS

  -- 
  -- DO NOT EDIT THIS FILE - it is machine generated!
  -- 

  args   JNI.ARGLIST;

  -- Method: arraycopy (Ljava/lang/Object;ILjava/lang/Object;II)V
  PROCEDURE arraycopy(
    a0    ORA_JAVA.JOBJECT,
    a1    NUMBER,
    a2    ORA_JAVA.JOBJECT,
    a3    NUMBER,
    a4    NUMBER) IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(5);
    JNI.ADD_OBJECT_ARG(args, a0, 'java/lang/Object');
    JNI.ADD_INT_ARG(args, a1);
    JNI.ADD_OBJECT_ARG(args, a2, 'java/lang/Object');
    JNI.ADD_INT_ARG(args, a3);
    JNI.ADD_INT_ARG(args, a4);
    JNI.CALL_VOID_METHOD(TRUE, NULL, 'java/lang/System', 'arraycopy', '(Ljava/lang/Object;ILjava/lang/Object;II)V', args); 
  END;

  -- Method: currentTimeMillis ()J
  FUNCTION currentTimeMillis RETURN NUMBER IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_LONG_METHOD(TRUE, NULL, 'java/lang/System', 'currentTimeMillis', '()J', args); 
  END;

  -- Method: identityHashCode (Ljava/lang/Object;)I
  FUNCTION identityHashCode(
    a0    ORA_JAVA.JOBJECT) RETURN NUMBER IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_OBJECT_ARG(args, a0, 'java/lang/Object');
    RETURN JNI.CALL_INT_METHOD(TRUE, NULL, 'java/lang/System', 'identityHashCode', '(Ljava/lang/Object;)I', args); 
  END;

  -- Method: exit (I)V
  PROCEDURE exit_(
    a0    NUMBER) IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_INT_ARG(args, a0);
    JNI.CALL_VOID_METHOD(TRUE, NULL, 'java/lang/System', 'exit', '(I)V', args); 
  END;

  -- Method: runFinalizersOnExit (Z)V
  PROCEDURE runFinalizersOnExit(
    a0    BOOLEAN) IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_BOOLEAN_ARG(args, a0);
    JNI.CALL_VOID_METHOD(TRUE, NULL, 'java/lang/System', 'runFinalizersOnExit', '(Z)V', args); 
  END;

  -- Method: setProperty (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
  FUNCTION setProperty(
    a0    VARCHAR2,
    a1    VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(2);
    JNI.ADD_STRING_ARG(args, a0);
    JNI.ADD_STRING_ARG(args, a1);
    RETURN JNI.CALL_STRING_METHOD(TRUE, NULL, 'java/lang/System', 'setProperty', '(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;', args); 
  END;

  -- Method: getProperty (Ljava/lang/String;)Ljava/lang/String;
  FUNCTION getProperty(
    a0    VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_STRING_ARG(args, a0);
    RETURN JNI.CALL_STRING_METHOD(TRUE, NULL, 'java/lang/System', 'getProperty', '(Ljava/lang/String;)Ljava/lang/String;', args); 
  END;

  -- Method: getProperty (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
  FUNCTION getProperty(
    a0    VARCHAR2,
    a1    VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(2);
    JNI.ADD_STRING_ARG(args, a0);
    JNI.ADD_STRING_ARG(args, a1);
    RETURN JNI.CALL_STRING_METHOD(TRUE, NULL, 'java/lang/System', 'getProperty', '(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;', args); 
  END;

  -- Method: getSecurityManager ()Ljava/lang/SecurityManager;
  FUNCTION getSecurityManager RETURN ORA_JAVA.JOBJECT IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_OBJECT_METHOD(TRUE, NULL, 'java/lang/System', 'getSecurityManager', '()Ljava/lang/SecurityManager;', args); 
  END;

  -- Method: load (Ljava/lang/String;)V
  PROCEDURE load(
    a0    VARCHAR2) IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_STRING_ARG(args, a0);
    JNI.CALL_VOID_METHOD(TRUE, NULL, 'java/lang/System', 'load', '(Ljava/lang/String;)V', args); 
  END;

  -- Method: loadLibrary (Ljava/lang/String;)V
  PROCEDURE loadLibrary(
    a0    VARCHAR2) IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_STRING_ARG(args, a0);
    JNI.CALL_VOID_METHOD(TRUE, NULL, 'java/lang/System', 'loadLibrary', '(Ljava/lang/String;)V', args); 
  END;

  -- Method: mapLibraryName (Ljava/lang/String;)Ljava/lang/String;
  FUNCTION mapLibraryName(
    a0    VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_STRING_ARG(args, a0);
    RETURN JNI.CALL_STRING_METHOD(TRUE, NULL, 'java/lang/System', 'mapLibraryName', '(Ljava/lang/String;)Ljava/lang/String;', args); 
  END;

  -- Method: gc ()V
  PROCEDURE gc IS
  BEGIN
    args := NULL;
    JNI.CALL_VOID_METHOD(TRUE, NULL, 'java/lang/System', 'gc', '()V', args); 
  END;

  -- Method: getProperties ()Ljava/util/Properties;
  FUNCTION getProperties RETURN ORA_JAVA.JOBJECT IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_OBJECT_METHOD(TRUE, NULL, 'java/lang/System', 'getProperties', '()Ljava/util/Properties;', args); 
  END;

  -- Method: getenv (Ljava/lang/String;)Ljava/lang/String;
  FUNCTION getenv(
    a0    VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_STRING_ARG(args, a0);
    RETURN JNI.CALL_STRING_METHOD(TRUE, NULL, 'java/lang/System', 'getenv', '(Ljava/lang/String;)Ljava/lang/String;', args); 
  END;

  -- Method: runFinalization ()V
  PROCEDURE runFinalization IS
  BEGIN
    args := NULL;
    JNI.CALL_VOID_METHOD(TRUE, NULL, 'java/lang/System', 'runFinalization', '()V', args); 
  END;

  -- Method: setErr (Ljava/io/PrintStream;)V
  PROCEDURE setErr(
    a0    ORA_JAVA.JOBJECT) IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_OBJECT_ARG(args, a0, 'java/io/PrintStream');
    JNI.CALL_VOID_METHOD(TRUE, NULL, 'java/lang/System', 'setErr', '(Ljava/io/PrintStream;)V', args); 
  END;

  -- Method: setIn (Ljava/io/InputStream;)V
  PROCEDURE setIn(
    a0    ORA_JAVA.JOBJECT) IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_OBJECT_ARG(args, a0, 'java/io/InputStream');
    JNI.CALL_VOID_METHOD(TRUE, NULL, 'java/lang/System', 'setIn', '(Ljava/io/InputStream;)V', args); 
  END;

  -- Method: setOut (Ljava/io/PrintStream;)V
  PROCEDURE setOut(
    a0    ORA_JAVA.JOBJECT) IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_OBJECT_ARG(args, a0, 'java/io/PrintStream');
    JNI.CALL_VOID_METHOD(TRUE, NULL, 'java/lang/System', 'setOut', '(Ljava/io/PrintStream;)V', args); 
  END;

  -- Method: setProperties (Ljava/util/Properties;)V
  PROCEDURE setProperties(
    a0    ORA_JAVA.JOBJECT) IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_OBJECT_ARG(args, a0, 'java/util/Properties');
    JNI.CALL_VOID_METHOD(TRUE, NULL, 'java/lang/System', 'setProperties', '(Ljava/util/Properties;)V', args); 
  END;

  -- Method: setSecurityManager (Ljava/lang/SecurityManager;)V
  PROCEDURE setSecurityManager(
    a0    ORA_JAVA.JOBJECT) IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_OBJECT_ARG(args, a0, 'java/lang/SecurityManager');
    JNI.CALL_VOID_METHOD(TRUE, NULL, 'java/lang/System', 'setSecurityManager', '(Ljava/lang/SecurityManager;)V', args); 
  END;

  -- Method: hashCode ()I
  FUNCTION hashCode(
    obj   ORA_JAVA.JOBJECT) RETURN NUMBER IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_INT_METHOD(FALSE, obj, 'java/lang/System', 'hashCode', '()I', args); 
  END;

  -- Method: getClass ()Ljava/lang/Class;
  FUNCTION getClass(
    obj   ORA_JAVA.JOBJECT) RETURN ORA_JAVA.JOBJECT IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_OBJECT_METHOD(FALSE, obj, 'java/lang/System', 'getClass', '()Ljava/lang/Class;', args); 
  END;

  -- Method: wait (JI)V
  PROCEDURE wait(
    obj   ORA_JAVA.JOBJECT,
    a0    NUMBER,
    a1    NUMBER) IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(2);
    JNI.ADD_LONG_ARG(args, a0);
    JNI.ADD_INT_ARG(args, a1);
    JNI.CALL_VOID_METHOD(FALSE, obj, 'java/lang/System', 'wait', '(JI)V', args); 
  END;

  -- Method: wait ()V
  PROCEDURE wait(
    obj   ORA_JAVA.JOBJECT) IS
  BEGIN
    args := NULL;
    JNI.CALL_VOID_METHOD(FALSE, obj, 'java/lang/System', 'wait', '()V', args); 
  END;

  -- Method: wait (J)V
  PROCEDURE wait(
    obj   ORA_JAVA.JOBJECT,
    a0    NUMBER) IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_LONG_ARG(args, a0);
    JNI.CALL_VOID_METHOD(FALSE, obj, 'java/lang/System', 'wait', '(J)V', args); 
  END;

  -- Method: equals (Ljava/lang/Object;)Z
  FUNCTION equals(
    obj   ORA_JAVA.JOBJECT,
    a0    ORA_JAVA.JOBJECT) RETURN BOOLEAN IS
  BEGIN
    args := JNI.CREATE_ARG_LIST(1);
    JNI.ADD_OBJECT_ARG(args, a0, 'java/lang/Object');
    RETURN JNI.CALL_BOOLEAN_METHOD(FALSE, obj, 'java/lang/System', 'equals', '(Ljava/lang/Object;)Z', args); 
  END;

  -- Method: notify ()V
  PROCEDURE notify(
    obj   ORA_JAVA.JOBJECT) IS
  BEGIN
    args := NULL;
    JNI.CALL_VOID_METHOD(FALSE, obj, 'java/lang/System', 'notify', '()V', args); 
  END;

  -- Method: notifyAll ()V
  PROCEDURE notifyAll(
    obj   ORA_JAVA.JOBJECT) IS
  BEGIN
    args := NULL;
    JNI.CALL_VOID_METHOD(FALSE, obj, 'java/lang/System', 'notifyAll', '()V', args); 
  END;

  -- Method: toString ()Ljava/lang/String;
  FUNCTION toString(
    obj   ORA_JAVA.JOBJECT) RETURN VARCHAR2 IS
  BEGIN
    args := NULL;
    RETURN JNI.CALL_STRING_METHOD(FALSE, obj, 'java/lang/System', 'toString', '()Ljava/lang/String;', args); 
  END;


BEGIN
  -- in (Ljava/io/InputStream;)
  in_ := JNI.GET_OBJECT_FIELD(TRUE, NULL, 'java/lang/System', 'in', 'Ljava/io/InputStream;');

  -- out (Ljava/io/PrintStream;)
  out_ := JNI.GET_OBJECT_FIELD(TRUE, NULL, 'java/lang/System', 'out', 'Ljava/io/PrintStream;');

  -- err (Ljava/io/PrintStream;)
  err := JNI.GET_OBJECT_FIELD(TRUE, NULL, 'java/lang/System', 'err', 'Ljava/io/PrintStream;');

END;
		*/
				//  
		//  DO NOT EDIT THIS FILE - it is machine generated!
		//  
		private UnknownTypes.JniArglist args= null;
/* <p>
		*  Method: arraycopy (Ljava/lang/Object;ILjava/lang/Object;II)V
		* F2J_PURE_BUSINESS_LOGIC : The code of this procedure was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param a0
		* @param a1
		* @param a2
		* @param a3
		* @param a4
		*/
		public void arraycopy(UnknownTypes.OraJavaJobject a0, NNumber a1, UnknownTypes.OraJavaJobject a2, NNumber a3, NNumber a4)
		{
			//F2J_WRAPPED_CODE : The code of this Procedure was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(5);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_OBJECT_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6".
//			//			SupportClasses.JNI.AddObjectArg(args, a0, "java/lang/Object");
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_OBJECT_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_INT_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin7".
//			//			SupportClasses.JNI.AddIntArg(args, a1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_INT_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin7'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_OBJECT_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6".
//			//			SupportClasses.JNI.AddObjectArg(args, a2, "java/lang/Object");
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_OBJECT_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_INT_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin7".
//			//			SupportClasses.JNI.AddIntArg(args, a3);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_INT_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin7'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_INT_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin7".
//			//			SupportClasses.JNI.AddIntArg(args, a4);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_INT_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin7'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "CALL_VOID_METHOD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8".
//			//			SupportClasses.JNI.CallVoidMethod(NBool.True, null, "java/lang/System", "arraycopy", "(Ljava/lang/Object;ILjava/lang/Object;II)V", args);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CALL_VOID_METHOD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8'.");
//			
//
			this.getLogger().trace(this, "F2J : arraycopy procedure is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
/* <p>
		*  Method: currentTimeMillis ()J
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		*/
		public NNumber currenttimemillis()
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallLongMethod(NBool.True, null, "java/lang/System", "currentTimeMillis", "()J", args);
//
			this.getLogger().trace(this, "F2J : currenttimemillis function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NNumber.getNull();
		}
/* <p>
		*  Method: identityHashCode (Ljava/lang/Object;)I
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param a0
		*/
		public NNumber identityhashcode(UnknownTypes.OraJavaJobject a0)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_OBJECT_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6".
//			//			SupportClasses.JNI.AddObjectArg(args, a0, "java/lang/Object");
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_OBJECT_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6'.");
//			
//			return SupportClasses.JNI.CallIntMethod(NBool.True, null, "java/lang/System", "identityHashCode", "(Ljava/lang/Object;)I", args);
//
			this.getLogger().trace(this, "F2J : identityhashcode function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NNumber.getNull();
		}
/* <p>
		*  Method: exit (I)V
		* F2J_PURE_BUSINESS_LOGIC : The code of this procedure was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param a0
		*/
		public void exit_(NNumber a0)
		{
			//F2J_WRAPPED_CODE : The code of this Procedure was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_INT_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin7".
//			//			SupportClasses.JNI.AddIntArg(args, a0);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_INT_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin7'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "CALL_VOID_METHOD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8".
//			//			SupportClasses.JNI.CallVoidMethod(NBool.True, null, "java/lang/System", "exit", "(I)V", args);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CALL_VOID_METHOD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8'.");
//			
//
			this.getLogger().trace(this, "F2J : exit_ procedure is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
/* <p>
		*  Method: runFinalizersOnExit (Z)V
		* F2J_PURE_BUSINESS_LOGIC : The code of this procedure was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param a0
		*/
		public void runfinalizersonexit(NBool a0)
		{
			//F2J_WRAPPED_CODE : The code of this Procedure was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_BOOLEAN_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin9".
//			//			SupportClasses.JNI.AddBooleanArg(args, a0);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_BOOLEAN_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin9'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "CALL_VOID_METHOD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8".
//			//			SupportClasses.JNI.CallVoidMethod(NBool.True, null, "java/lang/System", "runFinalizersOnExit", "(Z)V", args);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CALL_VOID_METHOD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8'.");
//			
//
			this.getLogger().trace(this, "F2J : runfinalizersonexit procedure is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
/* <p>
		*  Method: setProperty (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param a0
		* @param a1
		*/
		public NString setproperty(NString a0, NString a1)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(2);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_STRING_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10".
//			//			SupportClasses.JNI.AddStringArg(args, a0);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_STRING_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_STRING_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10".
//			//			SupportClasses.JNI.AddStringArg(args, a1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_STRING_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10'.");
//			
//			return SupportClasses.JNI.CallStringMethod(NBool.True, null, "java/lang/System", "setProperty", "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;", args);
//
			this.getLogger().trace(this, "F2J : setproperty function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NString.getNull();
		}
/* <p>
		*  Method: getProperty (Ljava/lang/String;)Ljava/lang/String;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param a0
		*/
		public NString getproperty(NString a0)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_STRING_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10".
//			//			SupportClasses.JNI.AddStringArg(args, a0);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_STRING_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10'.");
//			
//			return SupportClasses.JNI.CallStringMethod(NBool.True, null, "java/lang/System", "getProperty", "(Ljava/lang/String;)Ljava/lang/String;", args);
//
			this.getLogger().trace(this, "F2J : getproperty function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NString.getNull();
		}
/* <p>
		*  Method: getProperty (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param a0
		* @param a1
		*/
		public NString getproperty(NString a0, NString a1)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(2);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_STRING_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10".
//			//			SupportClasses.JNI.AddStringArg(args, a0);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_STRING_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_STRING_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10".
//			//			SupportClasses.JNI.AddStringArg(args, a1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_STRING_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10'.");
//			
//			return SupportClasses.JNI.CallStringMethod(NBool.True, null, "java/lang/System", "getProperty", "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;", args);
//
			this.getLogger().trace(this, "F2J : getproperty function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NString.getNull();
		}
/* <p>
		*  Method: getSecurityManager ()Ljava/lang/SecurityManager;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		*/
		public UnknownTypes.OraJavaJobject getsecuritymanager()
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallObjectMethod(NBool.True, null, "java/lang/System", "getSecurityManager", "()Ljava/lang/SecurityManager;", args);
//
			this.getLogger().trace(this, "F2J : getsecuritymanager function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return null;
		}
/* <p>
		*  Method: load (Ljava/lang/String;)V
		* F2J_PURE_BUSINESS_LOGIC : The code of this procedure was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param a0
		*/
		public void load(NString a0)
		{
			//F2J_WRAPPED_CODE : The code of this Procedure was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_STRING_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10".
//			//			SupportClasses.JNI.AddStringArg(args, a0);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_STRING_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "CALL_VOID_METHOD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8".
//			//			SupportClasses.JNI.CallVoidMethod(NBool.True, null, "java/lang/System", "load", "(Ljava/lang/String;)V", args);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CALL_VOID_METHOD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8'.");
//			
//
			this.getLogger().trace(this, "F2J : load procedure is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
/* <p>
		*  Method: loadLibrary (Ljava/lang/String;)V
		* F2J_PURE_BUSINESS_LOGIC : The code of this procedure was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param a0
		*/
		public void loadlibrary(NString a0)
		{
			//F2J_WRAPPED_CODE : The code of this Procedure was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_STRING_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10".
//			//			SupportClasses.JNI.AddStringArg(args, a0);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_STRING_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "CALL_VOID_METHOD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8".
//			//			SupportClasses.JNI.CallVoidMethod(NBool.True, null, "java/lang/System", "loadLibrary", "(Ljava/lang/String;)V", args);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CALL_VOID_METHOD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8'.");
//			
//
			this.getLogger().trace(this, "F2J : loadlibrary procedure is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
/* <p>
		*  Method: mapLibraryName (Ljava/lang/String;)Ljava/lang/String;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param a0
		*/
		public NString maplibraryname(NString a0)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_STRING_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10".
//			//			SupportClasses.JNI.AddStringArg(args, a0);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_STRING_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10'.");
//			
//			return SupportClasses.JNI.CallStringMethod(NBool.True, null, "java/lang/System", "mapLibraryName", "(Ljava/lang/String;)Ljava/lang/String;", args);
//
			this.getLogger().trace(this, "F2J : maplibraryname function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NString.getNull();
		}
/* <p>
		*  Method: gc ()V
		* F2J_PURE_BUSINESS_LOGIC : The code of this procedure was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		*/
		public void gc()
		{
			//F2J_WRAPPED_CODE : The code of this Procedure was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			// F2J_NOT_SUPPORTED : Call to built-in "CALL_VOID_METHOD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8".
//			//			SupportClasses.JNI.CallVoidMethod(NBool.True, null, "java/lang/System", "gc", "()V", args);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CALL_VOID_METHOD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8'.");
//			
//
			this.getLogger().trace(this, "F2J : gc procedure is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
/* <p>
		*  Method: getProperties ()Ljava/util/Properties;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		*/
		public UnknownTypes.OraJavaJobject getproperties()
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallObjectMethod(NBool.True, null, "java/lang/System", "getProperties", "()Ljava/util/Properties;", args);
//
			this.getLogger().trace(this, "F2J : getproperties function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return null;
		}
/* <p>
		*  Method: getenv (Ljava/lang/String;)Ljava/lang/String;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param a0
		*/
		public NString getenv(NString a0)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_STRING_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10".
//			//			SupportClasses.JNI.AddStringArg(args, a0);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_STRING_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin10'.");
//			
//			return SupportClasses.JNI.CallStringMethod(NBool.True, null, "java/lang/System", "getenv", "(Ljava/lang/String;)Ljava/lang/String;", args);
//
			this.getLogger().trace(this, "F2J : getenv function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NString.getNull();
		}
/* <p>
		*  Method: runFinalization ()V
		* F2J_PURE_BUSINESS_LOGIC : The code of this procedure was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		*/
		public void runfinalization()
		{
			//F2J_WRAPPED_CODE : The code of this Procedure was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			// F2J_NOT_SUPPORTED : Call to built-in "CALL_VOID_METHOD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8".
//			//			SupportClasses.JNI.CallVoidMethod(NBool.True, null, "java/lang/System", "runFinalization", "()V", args);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CALL_VOID_METHOD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8'.");
//			
//
			this.getLogger().trace(this, "F2J : runfinalization procedure is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
/* <p>
		*  Method: setErr (Ljava/io/PrintStream;)V
		* F2J_PURE_BUSINESS_LOGIC : The code of this procedure was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param a0
		*/
		public void seterr(UnknownTypes.OraJavaJobject a0)
		{
			//F2J_WRAPPED_CODE : The code of this Procedure was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_OBJECT_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6".
//			//			SupportClasses.JNI.AddObjectArg(args, a0, "java/io/PrintStream");
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_OBJECT_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "CALL_VOID_METHOD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8".
//			//			SupportClasses.JNI.CallVoidMethod(NBool.True, null, "java/lang/System", "setErr", "(Ljava/io/PrintStream;)V", args);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CALL_VOID_METHOD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8'.");
//			
//
			this.getLogger().trace(this, "F2J : seterr procedure is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
/* <p>
		*  Method: setIn (Ljava/io/InputStream;)V
		* F2J_PURE_BUSINESS_LOGIC : The code of this procedure was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param a0
		*/
		public void setin(UnknownTypes.OraJavaJobject a0)
		{
			//F2J_WRAPPED_CODE : The code of this Procedure was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_OBJECT_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6".
//			//			SupportClasses.JNI.AddObjectArg(args, a0, "java/io/InputStream");
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_OBJECT_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "CALL_VOID_METHOD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8".
//			//			SupportClasses.JNI.CallVoidMethod(NBool.True, null, "java/lang/System", "setIn", "(Ljava/io/InputStream;)V", args);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CALL_VOID_METHOD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8'.");
//			
//
			this.getLogger().trace(this, "F2J : setin procedure is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
/* <p>
		*  Method: setOut (Ljava/io/PrintStream;)V
		* F2J_PURE_BUSINESS_LOGIC : The code of this procedure was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param a0
		*/
		public void setout(UnknownTypes.OraJavaJobject a0)
		{
			//F2J_WRAPPED_CODE : The code of this Procedure was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_OBJECT_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6".
//			//			SupportClasses.JNI.AddObjectArg(args, a0, "java/io/PrintStream");
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_OBJECT_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "CALL_VOID_METHOD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8".
//			//			SupportClasses.JNI.CallVoidMethod(NBool.True, null, "java/lang/System", "setOut", "(Ljava/io/PrintStream;)V", args);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CALL_VOID_METHOD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8'.");
//			
//
			this.getLogger().trace(this, "F2J : setout procedure is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
/* <p>
		*  Method: setProperties (Ljava/util/Properties;)V
		* F2J_PURE_BUSINESS_LOGIC : The code of this procedure was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param a0
		*/
		public void setproperties(UnknownTypes.OraJavaJobject a0)
		{
			//F2J_WRAPPED_CODE : The code of this Procedure was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_OBJECT_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6".
//			//			SupportClasses.JNI.AddObjectArg(args, a0, "java/util/Properties");
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_OBJECT_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "CALL_VOID_METHOD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8".
//			//			SupportClasses.JNI.CallVoidMethod(NBool.True, null, "java/lang/System", "setProperties", "(Ljava/util/Properties;)V", args);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CALL_VOID_METHOD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8'.");
//			
//
			this.getLogger().trace(this, "F2J : setproperties procedure is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
/* <p>
		*  Method: setSecurityManager (Ljava/lang/SecurityManager;)V
		* F2J_PURE_BUSINESS_LOGIC : The code of this procedure was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param a0
		*/
		public void setsecuritymanager(UnknownTypes.OraJavaJobject a0)
		{
			//F2J_WRAPPED_CODE : The code of this Procedure was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_OBJECT_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6".
//			//			SupportClasses.JNI.AddObjectArg(args, a0, "java/lang/SecurityManager");
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_OBJECT_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "CALL_VOID_METHOD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8".
//			//			SupportClasses.JNI.CallVoidMethod(NBool.True, null, "java/lang/System", "setSecurityManager", "(Ljava/lang/SecurityManager;)V", args);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CALL_VOID_METHOD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8'.");
//			
//
			this.getLogger().trace(this, "F2J : setsecuritymanager procedure is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
/* <p>
		*  Method: hashCode ()I
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public NNumber hashcode(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallIntMethod(NBool.False, obj, "java/lang/System", "hashCode", "()I", args);
//
			this.getLogger().trace(this, "F2J : hashcode function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NNumber.getNull();
		}
/* <p>
		*  Method: getClass ()Ljava/lang/Class;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public UnknownTypes.OraJavaJobject getclass(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallObjectMethod(NBool.False, obj, "java/lang/System", "getClass", "()Ljava/lang/Class;", args);
//
			this.getLogger().trace(this, "F2J : getclass function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return null;
		}
/* <p>
		*  Method: wait (JI)V
		* F2J_PURE_BUSINESS_LOGIC : The code of this procedure was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		* @param a0
		* @param a1
		*/
		public void wait(UnknownTypes.OraJavaJobject obj, NNumber a0, NNumber a1)
		{
			//F2J_WRAPPED_CODE : The code of this Procedure was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(2);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_LONG_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin11".
//			//			SupportClasses.JNI.AddLongArg(args, a0);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_LONG_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin11'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_INT_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin7".
//			//			SupportClasses.JNI.AddIntArg(args, a1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_INT_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin7'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "CALL_VOID_METHOD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8".
//			//			SupportClasses.JNI.CallVoidMethod(NBool.False, obj, "java/lang/System", "wait", "(JI)V", args);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CALL_VOID_METHOD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8'.");
//			
//
			this.getLogger().trace(this, "F2J : wait procedure is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
/* <p>
		*  Method: wait ()V
		* F2J_PURE_BUSINESS_LOGIC : The code of this procedure was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public void wait(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Procedure was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			// F2J_NOT_SUPPORTED : Call to built-in "CALL_VOID_METHOD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8".
//			//			SupportClasses.JNI.CallVoidMethod(NBool.False, obj, "java/lang/System", "wait", "()V", args);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CALL_VOID_METHOD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8'.");
//			
//
			this.getLogger().trace(this, "F2J : wait procedure is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
/* <p>
		*  Method: wait (J)V
		* F2J_PURE_BUSINESS_LOGIC : The code of this procedure was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		* @param a0
		*/
		public void wait(UnknownTypes.OraJavaJobject obj, NNumber a0)
		{
			//F2J_WRAPPED_CODE : The code of this Procedure was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_LONG_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin11".
//			//			SupportClasses.JNI.AddLongArg(args, a0);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_LONG_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin11'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "CALL_VOID_METHOD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8".
//			//			SupportClasses.JNI.CallVoidMethod(NBool.False, obj, "java/lang/System", "wait", "(J)V", args);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CALL_VOID_METHOD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8'.");
//			
//
			this.getLogger().trace(this, "F2J : wait procedure is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
/* <p>
		*  Method: equals (Ljava/lang/Object;)Z
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		* @param a0
		*/
		public NBool equals(UnknownTypes.OraJavaJobject obj, UnknownTypes.OraJavaJobject a0)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			// F2J_NOT_SUPPORTED : Call to built-in "CREATE_ARG_LIST" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5".
//			//			args = SupportClasses.JNI.CreateArgList(1);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CREATE_ARG_LIST' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin5'.");
//			
//			// F2J_NOT_SUPPORTED : Call to built-in "ADD_OBJECT_ARG" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6".
//			//			SupportClasses.JNI.AddObjectArg(args, a0, "java/lang/Object");
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'ADD_OBJECT_ARG' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin6'.");
//			
//			return SupportClasses.JNI.CallBooleanMethod(NBool.False, obj, "java/lang/System", "equals", "(Ljava/lang/Object;)Z", args);
//
			this.getLogger().trace(this, "F2J : equals function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NBool.getNull();
		}
/* <p>
		*  Method: notify ()V
		* F2J_PURE_BUSINESS_LOGIC : The code of this procedure was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public void notify(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Procedure was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			// F2J_NOT_SUPPORTED : Call to built-in "CALL_VOID_METHOD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8".
//			//			SupportClasses.JNI.CallVoidMethod(NBool.False, obj, "java/lang/System", "notify", "()V", args);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CALL_VOID_METHOD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8'.");
//			
//
			this.getLogger().trace(this, "F2J : notify procedure is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
/* <p>
		*  Method: notifyAll ()V
		* F2J_PURE_BUSINESS_LOGIC : The code of this procedure was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public void notifyall(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Procedure was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			// F2J_NOT_SUPPORTED : Call to built-in "CALL_VOID_METHOD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8".
//			//			SupportClasses.JNI.CallVoidMethod(NBool.False, obj, "java/lang/System", "notifyAll", "()V", args);
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'CALL_VOID_METHOD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin8'.");
//			
//
			this.getLogger().trace(this, "F2J : notifyall procedure is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
/* <p>
		*  Method: toString ()Ljava/lang/String;
		* F2J_PURE_BUSINESS_LOGIC : The code of this function was identified as containing business logic. See documentation for details ms-help://atx.forms2net.en/Forms2NetHelp/html/MigrationGuide.html.
/* </p>
		* @param obj
		*/
		public NString tostring(UnknownTypes.OraJavaJobject obj)
		{
			//F2J_WRAPPED_CODE : The code of this Function was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			args = null;
//			return SupportClasses.JNI.CallStringMethod(NBool.False, obj, "java/lang/System", "toString", "()Ljava/lang/String;", args);
//
			this.getLogger().trace(this, "F2J : tostring function is not completely migrated yet. Please read the Migration Guide.");
			
			
			return NString.getNull();
		}
		public JavaSystem() {
			//F2J_WRAPPED_CODE : The code of this Package Constructor was commented out so that you can migrate, compile and check your code in an iterative way.
//
//			//  in (Ljava/io/InputStream;)
//			// F2J_NOT_SUPPORTED : Call to built-in "GET_OBJECT_FIELD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin12".
//			//			in_ = SupportClasses.JNI.GetObjectField(NBool.True, null, "java/lang/System", "in", "Ljava/io/InputStream;");
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'GET_OBJECT_FIELD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin12'.");
//			
//			//  out (Ljava/io/PrintStream;)
//			// F2J_NOT_SUPPORTED : Call to built-in "GET_OBJECT_FIELD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin12".
//			//			out_ = SupportClasses.JNI.GetObjectField(NBool.True, null, "java/lang/System", "out", "Ljava/io/PrintStream;");
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'GET_OBJECT_FIELD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin12'.");
//			
//			//  err (Ljava/io/PrintStream;)
//			// F2J_NOT_SUPPORTED : Call to built-in "GET_OBJECT_FIELD" was removed because it is not supported. See documentation for details "file://D:\Work\forms2net\Projects\Ellucian\Conversion\Docs\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin12".
//			//			err = SupportClasses.JNI.GetObjectField(NBool.True, null, "java/lang/System", "err", "Ljava/io/PrintStream;");
//			////
//			System.err.println("// F2J_NOT_SUPPORTED : Call to built-in 'GET_OBJECT_FIELD' was removed because it is not supported. See documentation for details 'file://D:\\Work\\forms2net\\Projects\\Ellucian\\Conversion\\Docs\\WEBUTILF2NMigrationGuide.xml#DefaultExcludeBuiltin12'.");
//			
//
			this.getLogger().trace(this, "F2J : JavaSystem Constructor is not completely migrated yet. Please read the Migration Guide.");
			
			
		}
		
	
	
}
